import type {
  AIAgent,
  AdminEvent,
  AdminRole,
  AdminScreenDefinition,
  AdminScreenSurface,
  AdminVenue,
  Appeal,
  AuditLogEntry,
  Claim,
  Complaint,
  EnforcementAction,
  EvidenceItem,
  ModerationCase,
  Participant,
  PromotionCampaign,
  VenueOrganizerAccess,
} from "./admin-types";

export const roleLabels: Record<AdminRole, string> = {
  organizer: "Организатор",
  venue_owner: "Владелец площадки",
  moderator: "Модератор",
};

export const roleBasePaths: Record<AdminRole, string> = {
  organizer: "/organizer",
  venue_owner: "/owner",
  moderator: "/moderator",
};

export const roleDescriptions: Record<AdminRole, string> = {
  organizer:
    "Создает события, ведет участников, чаты, AI-агентов, промо, выплаты и репутацию.",
  venue_owner:
    "Управляет площадками, политикой доступа, заявками организаторов, календарем и командой.",
  moderator:
    "Отвечает за безопасность платформы, claims, жалобы, enforcement, appeals и audit.",
};

export const rolePermissions: Record<AdminRole, string[]> = {
  organizer: [
    "event:create",
    "event:operate",
    "participant:manage",
    "chat:participant_reply",
    "promotion:own",
    "payout:own",
  ],
  venue_owner: [
    "venue:create",
    "venue:claim",
    "venue:edit_owned",
    "venue:policy",
    "venue:approve_organizer",
    "venue:approve_event_gate",
    "event:create",
  ],
  moderator: [
    "platform:event_gate",
    "moderation:complaint",
    "moderation:chat_evidence",
    "claim:verify",
    "enforcement:write",
    "audit:read",
  ],
};

export const adminEvents: AdminEvent[] = [
  {
    id: "evt_123",
    title: "Sunset Singles Mixer",
    organizerName: "The Penmar Events",
    venueName: "The Penmar",
    locationType: "external_venue",
    category: "Social / Music",
    date: "17 Apr 2026, 18:00",
    capacity: 80,
    ticketsSold: 42,
    revenue: 1050,
    refundPolicy: "Возврат до 24 часов до начала, затем только при отмене.",
    riskScore: 34,
    publicationStatus: "blocked_until_gates_pass",
    publicPreviewUrl: "/event/1",
    aiSummary:
      "AI предложил icebreakers, FAQ, промо-копи и подсказал, что внешняя площадка требует owner gate.",
    approvalGates: [
      {
        id: "gate_venue_123",
        type: "venue",
        actor: "venue_owner",
        status: "pending",
        venueId: "ven_456",
        requiredBecause: "Площадка требует одобрения каждого внешнего события.",
      },
      {
        id: "gate_platform_123",
        type: "platform",
        actor: "moderator",
        status: "approved",
        decidedBy: "Nina M.",
        decidedAt: "Сегодня, 10:12",
        requiredBecause: "Новая кампания с платными билетами прошла content scan.",
      },
    ],
  },
  {
    id: "evt_124",
    title: "AI Networking Breakfast",
    organizerName: "Dots Cafe",
    venueName: "Dots Cafe",
    locationType: "own_venue",
    category: "Networking",
    date: "19 Apr 2026, 08:30",
    capacity: 36,
    ticketsSold: 25,
    revenue: 625,
    refundPolicy: "Гибкий возврат до 12 часов до события.",
    riskScore: 12,
    publicationStatus: "ready_to_publish",
    publicPreviewUrl: "/event/2",
    aiSummary:
      "Низкий риск. Venue gate не требуется, так как организатор владеет площадкой.",
    approvalGates: [
      {
        id: "gate_venue_124",
        type: "venue",
        actor: "venue_owner",
        status: "not_required",
        requiredBecause: "Событие проходит на собственной площадке.",
      },
      {
        id: "gate_platform_124",
        type: "platform",
        actor: "moderator",
        status: "approved",
        decidedBy: "Auto policy",
        decidedAt: "Вчера, 16:40",
        requiredBecause: "Автопроверка не нашла запрещенного контента.",
      },
    ],
  },
  {
    id: "evt_125",
    title: "Late Night Warehouse Party",
    organizerName: "Unsafe Events LLC",
    venueName: "Private Warehouse",
    locationType: "external_venue",
    category: "Nightlife",
    date: "20 Apr 2026, 23:30",
    capacity: 250,
    ticketsSold: 0,
    revenue: 0,
    refundPolicy: "Не указана.",
    riskScore: 91,
    publicationStatus: "blocked_until_gates_pass",
    publicPreviewUrl: "/event/3",
    aiSummary:
      "Высокий риск: отсутствует venue proof, late-night alcohol signals, refund policy missing.",
    approvalGates: [
      {
        id: "gate_venue_125",
        type: "venue",
        actor: "venue_owner",
        status: "escalated",
        venueId: "ven_warehouse",
        requiredBecause: "Заявлены чужая площадка и высокая вместимость.",
      },
      {
        id: "gate_platform_125",
        type: "platform",
        actor: "moderator",
        status: "rejected",
        reason: "missing_safety_plan",
        decidedBy: "Nina M.",
        decidedAt: "Сегодня, 09:05",
        requiredBecause: "Policy scan поднял safety/fraud flags.",
      },
    ],
  },
];

export const adminVenues: AdminVenue[] = [
  {
    id: "ven_456",
    name: "The Penmar",
    address: "1234 Rose Ave",
    city: "Los Angeles",
    capacity: 120,
    ownerName: "The Penmar Group",
    claimStatus: "approved",
    policy: {
      mode: "moderate_every_event",
      allowRecurring: false,
      setupBufferMinutes: 60,
      restrictedCategories: ["Late night", "Political campaign"],
    },
    amenities: ["Проектор", "Бар", "Патио", "Wi-Fi"],
    accessibility: ["Безбарьерный вход", "Доступный туалет"],
    rules: ["No events after 23:00", "Insurance required over 100 guests"],
    rating: 4.8,
  },
  {
    id: "ven_789",
    name: "Gallery Loft",
    address: "44 Arts District",
    city: "Los Angeles",
    capacity: 90,
    ownerName: "Loft Collective",
    claimStatus: "pending",
    policy: {
      mode: "approve_organizers",
      allowRecurring: true,
      setupBufferMinutes: 45,
      restrictedCategories: ["High-risk finance"],
    },
    amenities: ["Галерея", "Свет", "Звук"],
    accessibility: ["Лифт", "Широкие проходы"],
    rules: ["No open flame", "Setup ends by 22:00"],
    rating: 4.6,
  },
  {
    id: "ven_999",
    name: "Secret Garden",
    address: "Hidden address until approved",
    city: "Los Angeles",
    capacity: 45,
    ownerName: "Secret Garden LLC",
    claimStatus: "approved",
    policy: {
      mode: "no_external_events",
      allowRecurring: false,
      setupBufferMinutes: 90,
      restrictedCategories: ["All external events"],
    },
    amenities: ["Garden", "Tea service", "Outdoor stage"],
    accessibility: ["Step-free side entrance"],
    rules: ["External organizers are disabled", "Invite-only events"],
    rating: 4.9,
  },
];

export const organizerAccessRequests: VenueOrganizerAccess[] = [
  {
    id: "req_218",
    venueId: "ven_456",
    organizerName: "The Penmar Events",
    status: "pending",
    requestedAt: "18 мин назад",
    rating: 4.7,
    pastEvents: 18,
    complaintCount: 0,
    note: "Хочу проводить ежемесячный social mixer на 60-80 гостей.",
  },
  {
    id: "req_219",
    venueId: "ven_789",
    organizerName: "LA Design Club",
    status: "approved",
    requestedAt: "Вчера",
    rating: 4.9,
    pastEvents: 27,
    complaintCount: 1,
    note: "Нужны выставочные вечера без алкоголя.",
  },
  {
    id: "req_220",
    venueId: "ven_456",
    organizerName: "Night Owl Social",
    status: "changes_requested",
    requestedAt: "2 ч назад",
    rating: 3.8,
    pastEvents: 4,
    complaintCount: 3,
    note: "Планируется late-night event. Нужен safety plan.",
  },
];

export const participants: Participant[] = [
  {
    id: "p1",
    name: "Maya Robinson",
    email: "maya@example.com",
    status: "paid",
    ticketTier: "General",
    paid: 25,
    notes: "Returning guest, vegetarian note.",
    lastMessageAt: "12 мин назад",
  },
  {
    id: "p2",
    name: "Leo Kim",
    email: "leo@example.com",
    status: "applied",
    ticketTier: "VIP",
    paid: 0,
    notes: "First-time participant, application needs review.",
  },
  {
    id: "p3",
    name: "Sara Patel",
    email: "sara@example.com",
    status: "waitlist",
    ticketTier: "General",
    paid: 0,
    notes: "Requested +1 ticket.",
  },
  {
    id: "p4",
    name: "Dana Moore",
    email: "dana@example.com",
    status: "refund_requested",
    ticketTier: "General",
    paid: 25,
    notes: "Schedule conflict, refund within policy window.",
  },
  {
    id: "p5",
    name: "Jordan Blake",
    email: "jordan@example.com",
    status: "checked_in",
    ticketTier: "VIP",
    paid: 45,
    checkedInAt: "18:04",
    notes: "Checked in via QR.",
  },
];

export const aiAgents: AIAgent[] = [
  {
    id: "ai_event_1",
    name: "Sunset Event AI",
    ownerName: "The Penmar Events",
    scope: "event",
    mode: "draft_replies",
    confidenceThreshold: 0.78,
    forbiddenTopics: ["legal advice", "medical advice", "ticket exceptions"],
    escalationTriggers: ["refund dispute", "safety concern", "harassment"],
  },
  {
    id: "ai_org_1",
    name: "Organizer Concierge",
    ownerName: "The Penmar Events",
    scope: "organizer",
    mode: "auto_reply_escalate",
    confidenceThreshold: 0.84,
    forbiddenTopics: ["dating guarantees", "financial claims"],
    escalationTriggers: ["complaint", "press request", "venue conflict"],
  },
  {
    id: "ai_venue_1",
    name: "Venue Bot",
    ownerName: "The Penmar",
    scope: "venue",
    mode: "auto_reply_safe",
    confidenceThreshold: 0.82,
    forbiddenTopics: ["legal capacity advice", "medical emergencies"],
    escalationTriggers: ["accessibility complaint", "policy exception", "incident"],
  },
];

export const promotionCampaigns: PromotionCampaign[] = [
  {
    id: "promo_1",
    name: "Sunset Mixer Boost",
    ownerName: "The Penmar Events",
    targetEntity: "Sunset Singles Mixer",
    spend: 120,
    status: "pending",
    riskScore: 42,
    creativeSummary: "AI-generated headline, social image, referral link, SUNSET10 code.",
  },
  {
    id: "promo_2",
    name: "Gallery Friday Retargeting",
    ownerName: "LA Design Club",
    targetEntity: "Gallery Loft",
    spend: 80,
    status: "running",
    riskScore: 18,
    creativeSummary: "Lookalike targeting and campaign analytics active.",
  },
  {
    id: "promo_3",
    name: "Warehouse Flash Sale",
    ownerName: "Unsafe Events LLC",
    targetEntity: "Late Night Warehouse Party",
    spend: 300,
    status: "escalated",
    riskScore: 88,
    creativeSummary: "Urgency claims, missing venue evidence, alcohol targeting.",
  },
];

export const complaints: Complaint[] = [
  {
    id: "cmp_301",
    targetType: "chat",
    targetName: "Sunset Mixer group chat",
    reporterName: "Maya Robinson",
    severity: "high",
    status: "new",
    summary: "Participant reported harassment in event chat.",
    evidenceCount: 4,
  },
  {
    id: "cmp_302",
    targetType: "event",
    targetName: "Late Night Warehouse Party",
    reporterName: "Venue owner",
    severity: "critical",
    status: "investigating",
    summary: "Possible unauthorized venue usage and unsafe capacity claims.",
    evidenceCount: 8,
  },
  {
    id: "cmp_303",
    targetType: "ai_agent",
    targetName: "Venue Bot",
    reporterName: "Organizer",
    severity: "medium",
    status: "new",
    summary: "AI answer promised a policy exception without owner approval.",
    evidenceCount: 2,
  },
];

export const claims: Claim[] = [
  {
    id: "clm_101",
    type: "venue",
    claimantName: "Loft Collective",
    targetName: "Gallery Loft",
    status: "pending",
    submittedAt: "Сегодня, 11:05",
    evidence: ["Business license", "Domain email", "Lease screenshot"],
  },
  {
    id: "clm_102",
    type: "organization",
    claimantName: "Dots Cafe",
    targetName: "Dots Cafe Events",
    status: "approved",
    submittedAt: "Вчера",
    evidence: ["Website ownership", "Tax document", "Phone verification"],
  },
];

export const moderationCases: ModerationCase[] = [
  {
    id: "case_1",
    type: "event",
    title: "Event approval: Sunset Singles Mixer",
    severity: "medium",
    status: "pending",
    assignee: "Nina M.",
    dueAt: "Сегодня, 17:00",
    summary: "Review venue gate, refund policy, AI-generated promo copy.",
  },
  {
    id: "case_2",
    type: "complaint",
    title: "Complaint: flagged chat harassment",
    severity: "high",
    status: "open",
    assignee: "Unassigned",
    dueAt: "Сегодня, 14:00",
    summary: "Evidence retained, participant safety action may be required.",
  },
  {
    id: "case_3",
    type: "promotion",
    title: "Promotion review: Warehouse Flash Sale",
    severity: "critical",
    status: "escalated",
    assignee: "Nina M.",
    dueAt: "Now",
    summary: "High-risk ad targeting, venue proof missing, campaign paused.",
  },
];

export const evidenceItems: EvidenceItem[] = [
  {
    id: "ev_1",
    caseId: "case_2",
    title: "Original chat transcript snapshot",
    source: "chat_snapshot",
    retainedUntil: "13 May 2027",
    hash: "sha256:8f16...91ab",
  },
  {
    id: "ev_2",
    caseId: "case_3",
    title: "AI creative generation trace",
    source: "ai_trace",
    retainedUntil: "13 May 2027",
    hash: "sha256:0c74...b331",
  },
  {
    id: "ev_3",
    caseId: "case_1",
    title: "Public preview at submission",
    source: "public_page",
    retainedUntil: "13 May 2027",
    hash: "sha256:a93e...71fa",
  },
];

export const enforcementActions: EnforcementAction[] = [
  {
    id: "enf_1",
    target: "Unsafe Events LLC",
    action: "suspension",
    status: "appealed",
    reasonCode: "missing_safety_plan",
    createdAt: "Сегодня, 09:10",
  },
  {
    id: "enf_2",
    target: "Venue Bot",
    action: "agent_limited",
    status: "active",
    reasonCode: "unsafe_ai_answer",
    createdAt: "Вчера, 18:45",
  },
  {
    id: "enf_3",
    target: "Chat message msg_448",
    action: "content_hidden",
    status: "active",
    reasonCode: "harassment",
    createdAt: "Сегодня, 12:20",
  },
];

export const appeals: Appeal[] = [
  {
    id: "apl_14",
    target: "Late Night Warehouse Party",
    originalDecision: "Event rejected: missing venue proof and safety plan.",
    status: "new",
    submittedAt: "Сегодня, 12:10",
    newEvidence: ["Venue letter", "Safety plan", "Capacity permit missing"],
  },
  {
    id: "apl_15",
    target: "Venue Bot enforcement",
    originalDecision: "Agent moved to draft-only until KB fix.",
    status: "under_review",
    submittedAt: "Вчера",
    newEvidence: ["Updated KB", "Owner acknowledgement"],
  },
];

export const auditLogs: AuditLogEntry[] = [
  {
    id: "aud_1",
    actor: "Nina M.",
    actorRole: "moderator",
    action: "Approved platform gate",
    entity: "Sunset Singles Mixer",
    reasonCode: "policy_clear",
    createdAt: "Сегодня, 10:12",
  },
  {
    id: "aud_2",
    actor: "Venue Owner",
    actorRole: "venue_owner",
    action: "Requested changes to event request",
    entity: "Night Owl Social",
    reasonCode: "missing_safety_plan",
    createdAt: "Сегодня, 09:50",
  },
  {
    id: "aud_3",
    actor: "The Penmar Events",
    actorRole: "organizer",
    action: "Submitted event for approval",
    entity: "Sunset Singles Mixer",
    createdAt: "Вчера, 16:20",
  },
];

export const organizerScreens: AdminScreenDefinition[] = [
  {
    slug: "dashboard",
    title: "Today",
    description: "Главная очередь действий организатора.",
    navGroup: "Работа",
    variant: "dashboard",
    requiredRole: "organizer",
    partialData: true,
  },
  {
    slug: "pipeline",
    title: "Events Pipeline",
    description: "Draft -> gates -> live -> settlement, без плоского approval status.",
    navGroup: "События",
    variant: "events",
    requiredRole: "organizer",
  },
  {
    slug: "events",
    title: "Events List",
    description: "Список событий с search, filters, bulk actions и gate status.",
    navGroup: "События",
    variant: "events",
    requiredRole: "organizer",
  },
  {
    slug: "calendar",
    title: "Event Calendar",
    description: "Календарь событий, approvals, ticket sales и reminders.",
    navGroup: "События",
    variant: "calendar",
    requiredRole: "organizer",
  },
  {
    slug: "create",
    title: "Create event",
    description: "A simple 5-step flow for hosting, location, guests, chat and preview.",
    navGroup: "Создание",
    variant: "create",
    requiredRole: "organizer",
  },
  {
    slug: "ai-builder",
    title: "Start with AI",
    description: "Describe the idea, generate a draft and continue in the same 5-step flow.",
    navGroup: "Создание",
    variant: "ai_builder",
    requiredRole: "organizer",
  },
  {
    slug: "venue-finder",
    title: "Venue Finder",
    description: "Поиск площадки с явной политикой доступа до создания события.",
    navGroup: "Площадки",
    variant: "venues",
    requiredRole: "organizer",
  },
  {
    slug: "venue-detail",
    title: "Venue Detail Preview",
    description: "Публичный профиль площадки, rules и request access.",
    navGroup: "Площадки",
    variant: "venue_detail",
    requiredRole: "organizer",
    detail: true,
  },
  {
    slug: "venue-requests",
    title: "Venue Request / Access Tracker",
    description: "Статусы доступа к внешним площадкам и requests на события.",
    navGroup: "Площадки",
    variant: "approvals",
    requiredRole: "organizer",
  },
  {
    slug: "approval-tracker",
    title: "Event Approval Tracker",
    description: "Venue gate + platform gate с независимыми decision owners.",
    navGroup: "События",
    variant: "event_detail",
    requiredRole: "organizer",
  },
  {
    slug: "workspace",
    title: "Event Workspace",
    description: "Операционная карточка события: участники, чат, tickets, payout.",
    navGroup: "События",
    variant: "event_detail",
    requiredRole: "organizer",
  },
  {
    slug: "participants",
    title: "Participants CRM",
    description: "Applications, approved, waitlist, paid, check-in, refunds, notes.",
    navGroup: "Операции",
    variant: "participants",
    requiredRole: "organizer",
  },
  {
    slug: "applications",
    title: "Applications Queue",
    description: "Очередь заявок с approve, reject, waitlist и notes.",
    navGroup: "Операции",
    variant: "participants",
    requiredRole: "organizer",
  },
  {
    slug: "waitlist",
    title: "Waitlist",
    description: "Управление очередью ожидания и capacity release.",
    navGroup: "Операции",
    variant: "participants",
    requiredRole: "organizer",
  },
  {
    slug: "tickets",
    title: "Tickets & Capacity",
    description: "Ticket tiers, capacity allocation, promo codes и refunds policy.",
    navGroup: "Операции",
    variant: "finance",
    requiredRole: "organizer",
  },
  {
    slug: "event-settings",
    title: "Event Settings & Audit",
    description: "Настройки события, опасные действия, версия изменений и event-level audit.",
    navGroup: "События",
    variant: "generic",
    requiredRole: "organizer",
    destructiveActions: true,
  },
  {
    slug: "chats",
    title: "Chats",
    description: "Event chat, DMs, announcements, AI drafts и escalation.",
    navGroup: "Коммуникации",
    variant: "chats",
    requiredRole: "organizer",
  },
  {
    slug: "direct-messages",
    title: "Direct Messages",
    description: "Единый inbox: participants, venue owners and support threads.",
    navGroup: "Коммуникации",
    variant: "chats",
    requiredRole: "organizer",
  },
  {
    slug: "announcements",
    title: "Announcements Composer",
    description: "Массовые сообщения участникам с audit trail.",
    navGroup: "Коммуникации",
    variant: "chats",
    requiredRole: "organizer",
  },
  {
    slug: "ai-draft-replies",
    title: "AI Draft Replies",
    description: "Review, edit, approve or reject AI reply drafts before sending.",
    navGroup: "Коммуникации",
    variant: "chats",
    requiredRole: "organizer",
  },
  {
    slug: "check-in",
    title: "Check-in Mode",
    description: "QR scanner state, manual check-in и offline fallback.",
    navGroup: "Операции",
    variant: "participants",
    requiredRole: "organizer",
    partialData: true,
  },
  {
    slug: "ai-agents",
    title: "AI Agents",
    description: "Event AI, Organizer AI, knowledge base, forbidden topics и test chat.",
    navGroup: "AI",
    variant: "ai_agents",
    requiredRole: "organizer",
  },
  {
    slug: "event-ai-agent",
    title: "Event AI Agent Settings",
    description: "Event-specific AI mode, forbidden topics, threshold and escalation triggers.",
    navGroup: "AI",
    variant: "ai_agents",
    requiredRole: "organizer",
  },
  {
    slug: "organizer-ai-agent",
    title: "Organizer AI Agent Settings",
    description: "Organizer-level AI agent for inbox, profile and recurring questions.",
    navGroup: "AI",
    variant: "ai_agents",
    requiredRole: "organizer",
  },
  {
    slug: "knowledge-base",
    title: "AI Knowledge Base",
    description: "FAQ, источники, failed answer review и confidence thresholds.",
    navGroup: "AI",
    variant: "ai_agents",
    requiredRole: "organizer",
  },
  {
    slug: "ai-test-conversation",
    title: "AI Test Conversation",
    description: "Safe test harness for AI responses before enabling auto-reply.",
    navGroup: "AI",
    variant: "ai_agents",
    requiredRole: "organizer",
  },
  {
    slug: "promotion",
    title: "Promotion Dashboard",
    description: "Boost credits, campaign builder, creative studio, attribution.",
    navGroup: "Рост",
    variant: "promotion",
    requiredRole: "organizer",
  },
  {
    slug: "promo-codes",
    title: "Promo Codes",
    description: "Discount codes, usage limits and attribution.",
    navGroup: "Рост",
    variant: "promotion",
    requiredRole: "organizer",
  },
  {
    slug: "campaign-builder",
    title: "Campaign Builder",
    description: "Targeting, referral links, promo codes и budget controls.",
    navGroup: "Рост",
    variant: "promotion",
    requiredRole: "organizer",
  },
  {
    slug: "creative-studio",
    title: "AI Creative Studio",
    description: "AI creatives with policy pre-check before risky campaign review.",
    navGroup: "Рост",
    variant: "promotion",
    requiredRole: "organizer",
  },
  {
    slug: "campaign-analytics",
    title: "Campaign Analytics",
    description: "Attribution, channel performance and promo conversion.",
    navGroup: "Рост",
    variant: "promotion",
    requiredRole: "organizer",
  },
  {
    slug: "analytics",
    title: "Event Analytics",
    description: "Funnel, no-show, retention, revenue and conversion.",
    navGroup: "Рост",
    variant: "finance",
    requiredRole: "organizer",
    partialData: true,
  },
  {
    slug: "payouts",
    title: "Payouts",
    description: "Ledger, KYC status, payout holds and event-level settlement.",
    navGroup: "Финансы",
    variant: "finance",
    requiredRole: "organizer",
    partialData: true,
  },
  {
    slug: "event-payouts",
    title: "Event Payouts",
    description: "Event-level settlement, platform fees, payout holds and ledger entries.",
    navGroup: "Финансы",
    variant: "finance",
    requiredRole: "organizer",
    partialData: true,
  },
  {
    slug: "refunds",
    title: "Refunds & Disputes",
    description: "Refund queue, chargebacks and support context.",
    navGroup: "Финансы",
    variant: "finance",
    requiredRole: "organizer",
    destructiveActions: true,
  },
  {
    slug: "disputes",
    title: "Disputes",
    description: "Chargebacks, evidence, participant context and support notes.",
    navGroup: "Финансы",
    variant: "finance",
    requiredRole: "organizer",
    destructiveActions: true,
  },
  {
    slug: "profile",
    title: "Organizer Profile Editor",
    description: "Редактирование публичного профиля организатора.",
    navGroup: "Профиль",
    variant: "generic",
    requiredRole: "organizer",
  },
  {
    slug: "public-profile-preview",
    title: "Organizer Public Preview Mobile",
    description: "Mobile QA preview for organizer public profile.",
    navGroup: "Профиль",
    variant: "generic",
    requiredRole: "organizer",
  },
  {
    slug: "reviews",
    title: "Reviews & Reputation",
    description: "Отзывы, ответы организатора и reputation signals.",
    navGroup: "Профиль",
    variant: "generic",
    requiredRole: "organizer",
  },
  {
    slug: "review-response",
    title: "Review Response",
    description: "Respond to participant reviews with policy-safe guidance.",
    navGroup: "Профиль",
    variant: "generic",
    requiredRole: "organizer",
  },
  {
    slug: "team",
    title: "Team & Permissions",
    description: "Роли команды, granular permissions and invites.",
    navGroup: "Настройки",
    variant: "team",
    requiredRole: "organizer",
  },
  {
    slug: "settings",
    title: "Organizer Settings",
    description: "Организация, notifications, integrations and safety preferences.",
    navGroup: "Настройки",
    variant: "generic",
    requiredRole: "organizer",
  },
  {
    slug: "audit-log",
    title: "Organizer Audit Log",
    description: "Журнал действий по событиям, участникам, чатам и промо.",
    navGroup: "Настройки",
    variant: "audit",
    requiredRole: "organizer",
  },
];

export const venueOwnerScreens: AdminScreenDefinition[] = [
  {
    slug: "dashboard",
    title: "Today",
    description: "Очередь владельца: requests, conflicts, calendar, venue health.",
    navGroup: "Работа",
    variant: "dashboard",
    requiredRole: "venue_owner",
    partialData: true,
  },
  {
    slug: "venues",
    title: "My Venues",
    description: "Список площадок, статусы claims, policy и quick actions.",
    navGroup: "Площадки",
    variant: "venues",
    requiredRole: "venue_owner",
  },
  {
    slug: "add-claim",
    title: "Add / Claim Venue",
    description: "Поиск, add venue, claim existing venue и evidence upload.",
    navGroup: "Площадки",
    variant: "create",
    requiredRole: "venue_owner",
  },
  {
    slug: "add-venue",
    title: "Add Venue",
    description: "Create a new owned venue profile after duplicate search.",
    navGroup: "Площадки",
    variant: "create",
    requiredRole: "venue_owner",
  },
  {
    slug: "claim-venue",
    title: "Claim Existing Venue",
    description: "Claim a pre-existing venue with ownership evidence.",
    navGroup: "Площадки",
    variant: "create",
    requiredRole: "venue_owner",
  },
  {
    slug: "claim-status",
    title: "Claim Verification Status",
    description: "Статус проверки ownership claim модератором.",
    navGroup: "Площадки",
    variant: "claims",
    requiredRole: "venue_owner",
  },
  {
    slug: "venue-detail",
    title: "Venue Detail",
    description: "Profile, rules, calendar, policy, inbox and audit for one venue.",
    navGroup: "Площадки",
    variant: "venue_detail",
    requiredRole: "venue_owner",
    detail: true,
  },
  {
    slug: "edit-profile",
    title: "Edit Venue Profile",
    description: "Photos, address, map, capacity, amenities, rules, accessibility.",
    navGroup: "Площадки",
    variant: "venue_detail",
    requiredRole: "venue_owner",
  },
  {
    slug: "photos",
    title: "Venue Photos",
    description: "Media gallery and public QA preview.",
    navGroup: "Площадки",
    variant: "venue_detail",
    requiredRole: "venue_owner",
  },
  {
    slug: "address-map",
    title: "Venue Address / Map",
    description: "Address, directions, map QA and visibility controls.",
    navGroup: "Площадки",
    variant: "venue_detail",
    requiredRole: "venue_owner",
  },
  {
    slug: "capacity-amenities",
    title: "Venue Capacity / Amenities",
    description: "Capacity limits, amenities, accessibility and restrictions.",
    navGroup: "Площадки",
    variant: "venue_detail",
    requiredRole: "venue_owner",
  },
  {
    slug: "rules",
    title: "Venue Rules",
    description: "House rules, blocked categories and public venue policy.",
    navGroup: "Площадки",
    variant: "policy",
    requiredRole: "venue_owner",
    destructiveActions: true,
  },
  {
    slug: "accessibility",
    title: "Venue Accessibility",
    description: "Accessibility details surfaced to organizers and guests.",
    navGroup: "Площадки",
    variant: "venue_detail",
    requiredRole: "venue_owner",
  },
  {
    slug: "access-policy",
    title: "Venue Access Policy",
    description: "Approve organizers, moderate every event, or no external events.",
    navGroup: "Approvals",
    variant: "policy",
    requiredRole: "venue_owner",
  },
  {
    slug: "approved-organizers",
    title: "Approved Organizers",
    description: "Approved external organizers and revocation audit.",
    navGroup: "Approvals",
    variant: "approvals",
    requiredRole: "venue_owner",
  },
  {
    slug: "blocked-organizers",
    title: "Blocked Organizers",
    description: "Venue-level blocked organizers with required reason codes.",
    navGroup: "Approvals",
    variant: "approvals",
    requiredRole: "venue_owner",
    destructiveActions: true,
  },
  {
    slug: "organizer-access",
    title: "Organizer Access Requests",
    description: "Approve, reject, ask question, or block organizer for venue.",
    navGroup: "Approvals",
    variant: "approvals",
    requiredRole: "venue_owner",
    destructiveActions: true,
  },
  {
    slug: "organizer-access-detail",
    title: "Organizer Access Request Detail",
    description: "Profile, past events, rating, complaint history and decision.",
    navGroup: "Approvals",
    variant: "approvals",
    requiredRole: "venue_owner",
    detail: true,
    destructiveActions: true,
  },
  {
    slug: "event-requests",
    title: "Event Requests Queue",
    description: "Owner approval queue for external events at owned venues.",
    navGroup: "Approvals",
    variant: "events",
    requiredRole: "venue_owner",
    destructiveActions: true,
  },
  {
    slug: "event-request-detail",
    title: "Event Request Detail",
    description: "Event details, conflicts, capacity, setup needs and venue gate decision.",
    navGroup: "Approvals",
    variant: "event_detail",
    requiredRole: "venue_owner",
    detail: true,
    destructiveActions: true,
  },
  {
    slug: "calendar",
    title: "Venue Calendar Month View",
    description: "Owned venue calendar by month.",
    navGroup: "Календарь",
    variant: "calendar",
    requiredRole: "venue_owner",
  },
  {
    slug: "calendar-week",
    title: "Venue Calendar Week View",
    description: "Week schedule, setup buffers and owner holds.",
    navGroup: "Календарь",
    variant: "calendar",
    requiredRole: "venue_owner",
  },
  {
    slug: "conflicts",
    title: "Schedule Conflict View",
    description: "Conflict detection when external requests overlap.",
    navGroup: "Календарь",
    variant: "calendar",
    requiredRole: "venue_owner",
    partialData: true,
  },
  {
    slug: "availability",
    title: "Availability & Blackout Dates",
    description: "Owner holds, blackout dates, recurring availability and conflict rules.",
    navGroup: "Календарь",
    variant: "calendar",
    requiredRole: "venue_owner",
  },
  {
    slug: "external-events",
    title: "External Events",
    description: "Approved and pending external events in owned venues.",
    navGroup: "События",
    variant: "events",
    requiredRole: "venue_owner",
  },
  {
    slug: "external-event-detail",
    title: "External Event Detail",
    description: "Read-only event details with owner-level actions only.",
    navGroup: "События",
    variant: "event_detail",
    requiredRole: "venue_owner",
    detail: true,
  },
  {
    slug: "my-events",
    title: "My Events",
    description: "Events created by the venue owner as organizer.",
    navGroup: "События",
    variant: "events",
    requiredRole: "venue_owner",
  },
  {
    slug: "create-event",
    title: "Create Event as Venue Owner",
    description: "Owner can create events in own venues, other venues, public or online.",
    navGroup: "События",
    variant: "create",
    requiredRole: "venue_owner",
  },
  {
    slug: "inbox",
    title: "Venue Inbox",
    description: "Organizer-owner threads and operational questions.",
    navGroup: "Операции",
    variant: "chats",
    requiredRole: "venue_owner",
  },
  {
    slug: "ai-agent",
    title: "Venue AI Agent Settings",
    description: "Venue AI mode, KB, forbidden topics and test conversation.",
    navGroup: "AI",
    variant: "ai_agents",
    requiredRole: "venue_owner",
  },
  {
    slug: "knowledge-base",
    title: "Venue Knowledge Base",
    description: "Parking, accessibility, rules, hours and owner FAQ.",
    navGroup: "AI",
    variant: "ai_agents",
    requiredRole: "venue_owner",
  },
  {
    slug: "promotion",
    title: "Venue Promotion",
    description: "Promote venues and own events with review for risky campaigns.",
    navGroup: "Рост",
    variant: "promotion",
    requiredRole: "venue_owner",
  },
  {
    slug: "analytics",
    title: "Venue Analytics",
    description: "Calendar utilization, external organizer quality, revenue signals.",
    navGroup: "Рост",
    variant: "finance",
    requiredRole: "venue_owner",
    partialData: true,
  },
  {
    slug: "reviews-complaints",
    title: "Venue Reviews & Complaints",
    description: "Venue-level reviews, complaints, owner responses and escalation context.",
    navGroup: "Рост",
    variant: "complaints",
    requiredRole: "venue_owner",
  },
  {
    slug: "public-preview",
    title: "Venue Public Preview Mobile",
    description: "Mobile QA preview for the public venue profile.",
    navGroup: "Рост",
    variant: "venue_detail",
    requiredRole: "venue_owner",
  },
  {
    slug: "team",
    title: "Venue Team & Permissions",
    description: "Staff access and role-based permissions.",
    navGroup: "Настройки",
    variant: "team",
    requiredRole: "venue_owner",
  },
  {
    slug: "settings",
    title: "Venue Settings",
    description: "Notifications, billing contacts, policy defaults and integrations.",
    navGroup: "Настройки",
    variant: "generic",
    requiredRole: "venue_owner",
  },
  {
    slug: "audit-log",
    title: "Venue Audit Log",
    description: "Venue profile, policy, approvals and team changes.",
    navGroup: "Настройки",
    variant: "audit",
    requiredRole: "venue_owner",
  },
];

export const moderatorScreens: AdminScreenDefinition[] = [
  {
    slug: "dashboard",
    title: "Review Queue",
    description: "Unified moderation queue for safety, claims, appeals and enforcement.",
    navGroup: "Очереди",
    variant: "moderation_queue",
    requiredRole: "moderator",
    partialData: true,
  },
  {
    slug: "events",
    title: "Event Approval Queue",
    description: "Platform gate decisions separated from venue gate decisions.",
    navGroup: "Очереди",
    variant: "events",
    requiredRole: "moderator",
    destructiveActions: true,
  },
  {
    slug: "event-approval-detail",
    title: "Event Approval Detail",
    description: "Content, organizer history, venue gate, scan, risk and refund policy.",
    navGroup: "Очереди",
    variant: "event_detail",
    requiredRole: "moderator",
    detail: true,
    destructiveActions: true,
  },
  {
    slug: "event-change-request",
    title: "Event Change Request",
    description: "Structured change request with blocked publish state and audit trail.",
    navGroup: "Очереди",
    variant: "event_detail",
    requiredRole: "moderator",
    detail: true,
    destructiveActions: true,
  },
  {
    slug: "complaints",
    title: "Complaint Queue",
    description: "Complaints about events, chats, organizers, venues and participants.",
    navGroup: "Trust & Safety",
    variant: "complaints",
    requiredRole: "moderator",
    destructiveActions: true,
  },
  {
    slug: "complaint-detail",
    title: "Complaint Detail",
    description: "Case context, reporter history, evidence and enforcement options.",
    navGroup: "Trust & Safety",
    variant: "complaints",
    requiredRole: "moderator",
    detail: true,
    destructiveActions: true,
  },
  {
    slug: "chat-moderation",
    title: "Chat Moderation Queue",
    description: "Only flagged/evidence chats, not global participant chat browsing.",
    navGroup: "Trust & Safety",
    variant: "chats",
    requiredRole: "moderator",
    destructiveActions: true,
  },
  {
    slug: "chat-moderation-detail",
    title: "Chat Moderation Detail",
    description: "Transcript review, hide/remove/lock with evidence retention.",
    navGroup: "Trust & Safety",
    variant: "chats",
    requiredRole: "moderator",
    detail: true,
    destructiveActions: true,
  },
  {
    slug: "evidence-vault",
    title: "Evidence Vault",
    description: "Original evidence retention after deletion, hiding or enforcement.",
    navGroup: "Trust & Safety",
    variant: "evidence",
    requiredRole: "moderator",
  },
  {
    slug: "organization-claims",
    title: "Organization Claim Queue",
    description: "Verify ownership claims for organizations.",
    navGroup: "Claims",
    variant: "claims",
    requiredRole: "moderator",
    destructiveActions: true,
  },
  {
    slug: "organization-claim-detail",
    title: "Organization Claim Detail",
    description: "Ownership evidence, domain, address and final role grant.",
    navGroup: "Claims",
    variant: "claims",
    requiredRole: "moderator",
    detail: true,
    destructiveActions: true,
  },
  {
    slug: "venue-claims",
    title: "Venue Claim Queue",
    description: "Verify venue ownership claims without self-approval.",
    navGroup: "Claims",
    variant: "claims",
    requiredRole: "moderator",
    destructiveActions: true,
  },
  {
    slug: "venue-claim-detail",
    title: "Venue Claim Detail",
    description: "Documents, listing match, address proof and claimant review.",
    navGroup: "Claims",
    variant: "claims",
    requiredRole: "moderator",
    detail: true,
    destructiveActions: true,
  },
  {
    slug: "ownership-evidence-review",
    title: "Ownership Evidence Review",
    description: "Compare documents, domain, address, public listing and claimant identity.",
    navGroup: "Claims",
    variant: "claims",
    requiredRole: "moderator",
    detail: true,
    destructiveActions: true,
  },
  {
    slug: "ai-safety",
    title: "AI Safety Dashboard",
    description: "AI agent violations, unsafe answers and agent enforcement.",
    navGroup: "AI Safety",
    variant: "ai_agents",
    requiredRole: "moderator",
    destructiveActions: true,
  },
  {
    slug: "ai-conversation-review",
    title: "AI Conversation Review",
    description: "AI answer, sources, confidence, forbidden topics and escalation.",
    navGroup: "AI Safety",
    variant: "ai_agents",
    requiredRole: "moderator",
    detail: true,
    destructiveActions: true,
  },
  {
    slug: "ai-agent-enforcement",
    title: "AI Agent Enforcement Drawer",
    description: "Limit agent mode, require KB fix and notify owner without nested modals.",
    navGroup: "AI Safety",
    variant: "ai_agents",
    requiredRole: "moderator",
    detail: true,
    destructiveActions: true,
  },
  {
    slug: "promotion-review",
    title: "Promotion Review Queue",
    description: "Campaigns and AI creatives that need policy review.",
    navGroup: "Promotion",
    variant: "promotion",
    requiredRole: "moderator",
    destructiveActions: true,
  },
  {
    slug: "promotion-review-detail",
    title: "Promotion Review Detail",
    description: "Creative, targeting, risk signals and promotion gate decision.",
    navGroup: "Promotion",
    variant: "promotion",
    requiredRole: "moderator",
    detail: true,
    destructiveActions: true,
  },
  {
    slug: "enforcement",
    title: "Enforcement Actions",
    description: "Warnings, suspensions, blocks, hidden content and appeal rights.",
    navGroup: "Enforcement",
    variant: "enforcement",
    requiredRole: "moderator",
    destructiveActions: true,
  },
  {
    slug: "enforcement-action-detail",
    title: "Enforcement Action Detail",
    description: "Reason code, policy section, evidence, notifications and appeal rights.",
    navGroup: "Enforcement",
    variant: "enforcement",
    requiredRole: "moderator",
    detail: true,
    destructiveActions: true,
  },
  {
    slug: "appeals",
    title: "Appeals Queue",
    description: "Appeals on reject, block and enforcement decisions.",
    navGroup: "Enforcement",
    variant: "appeals",
    requiredRole: "moderator",
    destructiveActions: true,
  },
  {
    slug: "appeal-detail",
    title: "Appeal Detail",
    description: "Original evidence vs new evidence with final decision audit.",
    navGroup: "Enforcement",
    variant: "appeals",
    requiredRole: "moderator",
    detail: true,
    destructiveActions: true,
  },
  {
    slug: "policy-rules",
    title: "Policy Rules",
    description: "Rules, auto-review thresholds and policy versions.",
    navGroup: "Policy",
    variant: "rules",
    requiredRole: "moderator",
  },
  {
    slug: "risk-rule-builder",
    title: "Risk Rule Builder",
    description: "Create and edit risk rules with dry-run impact.",
    navGroup: "Policy",
    variant: "rules",
    requiredRole: "moderator",
  },
  {
    slug: "audit-log",
    title: "Moderator Audit Log",
    description: "All moderation decisions, reason codes, evidence and actor trail.",
    navGroup: "Policy",
    variant: "audit",
    requiredRole: "moderator",
  },
  {
    slug: "moderation-analytics",
    title: "Moderation Analytics",
    description: "SLA, queue health, false positives and enforcement outcomes.",
    navGroup: "Policy",
    variant: "finance",
    requiredRole: "moderator",
    partialData: true,
  },
  {
    slug: "user-risk-profile",
    title: "User Risk Profile",
    description: "Read-only user risk profile for moderation investigation.",
    navGroup: "Policy",
    variant: "complaints",
    requiredRole: "moderator",
    detail: true,
  },
  {
    slug: "organization-risk-profile",
    title: "Organization Risk Profile",
    description: "Organization-level trust view with linked risky entities.",
    navGroup: "Policy",
    variant: "claims",
    requiredRole: "moderator",
    detail: true,
  },
  {
    slug: "payout-fraud-review",
    title: "Payout / Fraud Review",
    description: "Read-only financial context for fraud and dispute moderation.",
    navGroup: "Policy",
    variant: "finance",
    requiredRole: "moderator",
    partialData: true,
  },
  {
    slug: "team-settings",
    title: "Moderator Team Settings",
    description: "Assignees, queues, SLA policies and moderation team permissions.",
    navGroup: "Policy",
    variant: "team",
    requiredRole: "moderator",
  },
];

type ChildSurfaceConfig = {
  parentSlug: string;
  surfaceType: AdminScreenSurface["surfaceType"];
  prototypeRefs?: string[];
};

const primaryNavSlugs: Record<AdminRole, string[]> = {
  organizer: ["dashboard", "events", "messages", "profile", "money"],
  venue_owner: ["dashboard", "places", "requests", "calendar"],
  moderator: ["dashboard", "reports", "claims", "history"],
};

const primaryTitleOverrides: Record<AdminRole, Record<string, string>> = {
  organizer: {
    dashboard: "Today",
    create: "Create Event",
    events: "Events",
    messages: "Messages",
    profile: "Profile",
    money: "Money",
  },
  venue_owner: {
    dashboard: "Today",
    places: "Places",
    requests: "Requests",
    calendar: "Calendar",
  },
  moderator: {
    dashboard: "Queue",
    reports: "Reports",
    claims: "Claims",
    history: "History",
  },
};

const childSurfaces: Record<AdminRole, Record<string, ChildSurfaceConfig>> = {
  organizer: {
    pipeline: { parentSlug: "events", surfaceType: "tab", prototypeRefs: ["O02"] },
    calendar: { parentSlug: "events", surfaceType: "tab", prototypeRefs: ["O04"] },
    "approval-tracker": { parentSlug: "events", surfaceType: "detail_panel", prototypeRefs: ["O20", "E09"] },
    workspace: { parentSlug: "events", surfaceType: "detail_panel", prototypeRefs: ["O21"] },
    tickets: { parentSlug: "events", surfaceType: "tab", prototypeRefs: ["O24"] },
    analytics: { parentSlug: "events", surfaceType: "tab", prototypeRefs: ["O29"] },
    "event-settings": { parentSlug: "events", surfaceType: "action", prototypeRefs: ["O31", "E11"] },
    "venue-detail": { parentSlug: "venue-finder", surfaceType: "detail_panel", prototypeRefs: ["O19"] },
    applications: { parentSlug: "participants", surfaceType: "tab", prototypeRefs: ["O22"] },
    waitlist: { parentSlug: "participants", surfaceType: "tab", prototypeRefs: ["O22"] },
    "participant-detail": { parentSlug: "participants", surfaceType: "drawer", prototypeRefs: ["O23"] },
    "direct-messages": { parentSlug: "chats", surfaceType: "tab", prototypeRefs: ["O26"] },
    announcements: { parentSlug: "chats", surfaceType: "action", prototypeRefs: ["O27"] },
    "ai-draft-replies": { parentSlug: "chats", surfaceType: "tab", prototypeRefs: ["O25", "O26"] },
    "event-ai-agent": { parentSlug: "ai-agents", surfaceType: "tab", prototypeRefs: ["O33"] },
    "organizer-ai-agent": { parentSlug: "ai-agents", surfaceType: "tab", prototypeRefs: ["O32"] },
    "knowledge-base": { parentSlug: "ai-agents", surfaceType: "tab", prototypeRefs: ["O34"] },
    "ai-test-conversation": { parentSlug: "ai-agents", surfaceType: "tab", prototypeRefs: ["O34"] },
    "promo-codes": { parentSlug: "promotion", surfaceType: "tab", prototypeRefs: ["O35"] },
    "campaign-builder": { parentSlug: "promotion", surfaceType: "action", prototypeRefs: ["O35"] },
    "creative-studio": { parentSlug: "promotion", surfaceType: "tab", prototypeRefs: ["O36"] },
    "campaign-analytics": { parentSlug: "promotion", surfaceType: "tab", prototypeRefs: ["O37"] },
    "event-payouts": { parentSlug: "payouts", surfaceType: "tab", prototypeRefs: ["O30"] },
    refunds: { parentSlug: "payouts", surfaceType: "tab", prototypeRefs: ["O39"] },
    disputes: { parentSlug: "payouts", surfaceType: "tab", prototypeRefs: ["O39"] },
    "public-profile-preview": { parentSlug: "profile", surfaceType: "detail_panel", prototypeRefs: ["O41"] },
    "review-response": { parentSlug: "reviews", surfaceType: "drawer", prototypeRefs: ["O42"] },
  },
  venue_owner: {
    "add-venue": { parentSlug: "add-claim", surfaceType: "tab", prototypeRefs: ["V04"] },
    "claim-venue": { parentSlug: "add-claim", surfaceType: "tab", prototypeRefs: ["V05"] },
    "claim-status": { parentSlug: "add-claim", surfaceType: "tab", prototypeRefs: ["V06"] },
    "venue-detail": { parentSlug: "venues", surfaceType: "detail_panel", prototypeRefs: ["V07"] },
    "edit-profile": { parentSlug: "venues", surfaceType: "tab", prototypeRefs: ["V08"] },
    photos: { parentSlug: "venues", surfaceType: "tab", prototypeRefs: ["V09"] },
    "address-map": { parentSlug: "venues", surfaceType: "tab", prototypeRefs: ["V08"] },
    "capacity-amenities": { parentSlug: "venues", surfaceType: "tab", prototypeRefs: ["V08"] },
    rules: { parentSlug: "venues", surfaceType: "tab", prototypeRefs: ["V11"] },
    accessibility: { parentSlug: "venues", surfaceType: "tab", prototypeRefs: ["V08"] },
    "access-policy": { parentSlug: "venues", surfaceType: "tab", prototypeRefs: ["V10", "V11", "E12"] },
    "public-preview": { parentSlug: "venues", surfaceType: "detail_panel", prototypeRefs: ["V29"] },
    "calendar-week": { parentSlug: "calendar", surfaceType: "tab", prototypeRefs: ["V12"] },
    conflicts: { parentSlug: "calendar", surfaceType: "tab", prototypeRefs: ["V13"] },
    availability: { parentSlug: "venues", surfaceType: "tab", prototypeRefs: ["VEN-17"] },
    "approved-organizers": { parentSlug: "organizer-access", surfaceType: "tab", prototypeRefs: ["V18"] },
    "blocked-organizers": { parentSlug: "organizer-access", surfaceType: "tab", prototypeRefs: ["V19"] },
    "organizer-access-detail": { parentSlug: "organizer-access", surfaceType: "drawer", prototypeRefs: ["V15"] },
    "event-requests": { parentSlug: "organizer-access", surfaceType: "tab", prototypeRefs: ["V16"] },
    "event-request-detail": { parentSlug: "organizer-access", surfaceType: "drawer", prototypeRefs: ["V17"] },
    "external-event-detail": { parentSlug: "external-events", surfaceType: "drawer", prototypeRefs: ["V20"] },
    "create-event": { parentSlug: "my-events", surfaceType: "action", prototypeRefs: ["V21"] },
    "knowledge-base": { parentSlug: "ai-agent", surfaceType: "tab", prototypeRefs: ["V23"] },
    "reviews-complaints": { parentSlug: "analytics", surfaceType: "tab", prototypeRefs: ["V26"] },
  },
  moderator: {
    "event-approval-detail": { parentSlug: "events", surfaceType: "drawer", prototypeRefs: ["M04"] },
    "event-change-request": { parentSlug: "events", surfaceType: "action", prototypeRefs: ["M05"] },
    "complaint-detail": { parentSlug: "complaints", surfaceType: "drawer", prototypeRefs: ["M07"] },
    "chat-moderation-detail": { parentSlug: "chat-moderation", surfaceType: "drawer", prototypeRefs: ["M09"] },
    "venue-claims": { parentSlug: "organization-claims", surfaceType: "tab", prototypeRefs: ["M11"] },
    "organization-claim-detail": { parentSlug: "organization-claims", surfaceType: "drawer", prototypeRefs: ["M12"] },
    "venue-claim-detail": { parentSlug: "organization-claims", surfaceType: "drawer", prototypeRefs: ["M12"] },
    "ownership-evidence-review": { parentSlug: "organization-claims", surfaceType: "detail_panel", prototypeRefs: ["M13"] },
    "ai-conversation-review": { parentSlug: "ai-safety", surfaceType: "drawer", prototypeRefs: ["M15"] },
    "ai-agent-enforcement": { parentSlug: "ai-safety", surfaceType: "drawer", prototypeRefs: ["M16"] },
    "promotion-review-detail": { parentSlug: "promotion-review", surfaceType: "drawer", prototypeRefs: ["M18"] },
    "enforcement-action-detail": { parentSlug: "enforcement", surfaceType: "drawer", prototypeRefs: ["M20"] },
    "appeal-detail": { parentSlug: "appeals", surfaceType: "drawer", prototypeRefs: ["M22"] },
    "risk-rule-builder": { parentSlug: "policy-rules", surfaceType: "tab", prototypeRefs: ["M24"] },
    "moderation-analytics": { parentSlug: "audit-log", surfaceType: "tab", prototypeRefs: ["M26"] },
    "user-risk-profile": { parentSlug: "audit-log", surfaceType: "drawer", prototypeRefs: ["M27"] },
    "organization-risk-profile": { parentSlug: "audit-log", surfaceType: "drawer", prototypeRefs: ["M28"] },
    "payout-fraud-review": { parentSlug: "audit-log", surfaceType: "drawer", prototypeRefs: ["M29"] },
    "team-settings": { parentSlug: "audit-log", surfaceType: "tab", prototypeRefs: ["M30"] },
  },
};

const extraSurfaces: Record<AdminRole, Record<string, AdminScreenSurface[]>> = {
  organizer: {
    create: [
      {
        slug: "create/hosting",
        title: "What are you hosting?",
        description: "Event name, category, short description and cover image.",
        surfaceType: "wizard_step",
        variant: "create",
        prototypeRefs: ["create-v4"],
      },
      {
        slug: "create/where-when",
        title: "Where and when?",
        description: "Location type, venue or link, date, time and timezone.",
        surfaceType: "wizard_step",
        variant: "create",
        prototypeRefs: ["create-v4"],
      },
      {
        slug: "create/guests-tickets",
        title: "Guests and tickets",
        description: "Capacity, ticket price, RSVP style, waitlist and attendance rule.",
        surfaceType: "wizard_step",
        variant: "create",
        prototypeRefs: ["create-v4"],
      },
      {
        slug: "create/chat-ai",
        title: "Chat and AI helper",
        description: "Event chat, AI helper mode and simple FAQ.",
        surfaceType: "wizard_step",
        variant: "create",
        prototypeRefs: ["create-v4"],
      },
      {
        slug: "create/preview-publish",
        title: "Preview and publish",
        description: "Event card preview, missing fields and final publish action.",
        surfaceType: "wizard_step",
        variant: "create",
        prototypeRefs: ["create-v4"],
      },
    ],
    "ai-builder": [
      {
        slug: "ai-builder/prompt",
        title: "Start with AI",
        description: "Describe the event idea and generate a draft.",
        surfaceType: "wizard_step",
        variant: "ai_builder",
        prototypeRefs: ["create-v4"],
      },
      {
        slug: "ai-builder/generated-plan",
        title: "AI draft",
        description: "Review the generated event draft before editing the same wizard.",
        surfaceType: "wizard_step",
        variant: "ai_builder",
        prototypeRefs: ["create-v4"],
      },
      {
        slug: "ai-builder/review-edit",
        title: "Confirm fields",
        description: "Confirm the critical fields, then continue in the 5-step wizard.",
        surfaceType: "wizard_step",
        variant: "ai_builder",
        prototypeRefs: ["create-v4"],
      },
    ],
  },
  venue_owner: {
    "ai-agent": [
      {
        slug: "ai-agent/test-conversation",
        title: "Test Conversation",
        description: "Preview venue AI answers before enabling auto-reply.",
        surfaceType: "tab",
        variant: "ai_agents",
        prototypeRefs: ["V23"],
      },
    ],
  },
  moderator: {},
};

type RouteAliasConfig = {
  pattern: RegExp;
  targetSlug?: string;
  parentSlug?: string;
  surface?: AdminScreenSurface;
};

function exactRoute(value: string) {
  return new RegExp(`^${value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`);
}

function routeSurface(
  slug: string,
  title: string,
  description: string,
  surfaceType: AdminScreenSurface["surfaceType"],
  variant: AdminScreenDefinition["variant"],
  prototypeRefs?: string[],
): AdminScreenSurface {
  return { slug, title, description, surfaceType, variant, prototypeRefs };
}

function alias(
  pattern: string | RegExp,
  targetSlug: string,
): RouteAliasConfig {
  return {
    pattern: typeof pattern === "string" ? exactRoute(pattern) : pattern,
    targetSlug,
  };
}

function surfaceAlias(
  pattern: string | RegExp,
  parentSlug: string,
  surface: AdminScreenSurface,
): RouteAliasConfig {
  return {
    pattern: typeof pattern === "string" ? exactRoute(pattern) : pattern,
    parentSlug,
    surface,
  };
}

const v3RouteAliases: Record<AdminRole, RouteAliasConfig[]> = {
  organizer: [
    alias("assistant", "ai-builder"),
    alias("chats", "messages"),
    alias("direct-messages", "messages"),
    surfaceAlias("participants", "events", routeSurface("guests", "Guests", "Guest list, applications, waitlist and check-in.", "tab", "participants", ["v4"])),
    surfaceAlias("attendees", "events", routeSurface("guests", "Guests", "Guest list, applications, waitlist and check-in.", "tab", "participants", ["v4"])),
    surfaceAlias("applications", "events", routeSurface("guests", "Guests", "Guest list, applications, waitlist and check-in.", "tab", "participants", ["v4"])),
    surfaceAlias("waitlist", "events", routeSurface("guests", "Guests", "Guest list, applications, waitlist and check-in.", "tab", "participants", ["v4"])),
    surfaceAlias("check-in", "events", routeSurface("guests", "Guests", "Guest list, applications, waitlist and check-in.", "tab", "participants", ["v4"])),
    surfaceAlias("promotion", "events", routeSurface("promote", "Promote", "Boost, share link, promo code and AI promo copy.", "tab", "promotion", ["v4"])),
    surfaceAlias("promotion/new", "events", routeSurface("promote", "Promote", "Boost, share link, promo code and AI promo copy.", "tab", "promotion", ["v4"])),
    surfaceAlias("promotion/creative", "events", routeSurface("promote", "Promote", "Boost, share link, promo code and AI promo copy.", "tab", "promotion", ["v4"])),
    alias("payouts", "money"),
    alias("payouts/ledger", "money"),
    surfaceAlias("payouts/disputes", "events", routeSurface("event-money", "Money", "Event revenue, refunds and payout rows.", "tab", "finance", ["v4"])),
    surfaceAlias("ai-agents", "events", routeSurface("workspace-settings", "Settings", "Event AI mode, tickets, capacity and settings.", "tab", "generic", ["v4"])),
    surfaceAlias("ai/knowledge", "events", routeSurface("workspace-settings", "Settings", "Event AI mode, tickets, capacity and settings.", "tab", "generic", ["v4"])),
    surfaceAlias("ai/test", "events", routeSurface("chat", "Chat", "Test AI draft replies inside event chat.", "tab", "chats", ["v4"])),
    alias("events/pipeline", "pipeline"),
    alias("events/calendar", "calendar"),
    surfaceAlias(
      "templates",
      "events",
      routeSurface(
        "templates",
        "Event Templates",
        "Saved event, ticket, FAQ and AI settings templates.",
        "tab",
        "generic",
        ["ORG-05"],
      ),
    ),
    alias("events/new", "create/hosting"),
    alias("events/new/mode", "create/hosting"),
    alias("events/new/hosting", "create/hosting"),
    alias("events/new/basics", "create/hosting"),
    alias("events/new/location", "create/where-when"),
    alias("events/new/where-when", "create/where-when"),
    alias("events/new/schedule", "create/where-when"),
    alias("events/new/tickets", "create/guests-tickets"),
    alias("events/new/guests-tickets", "create/guests-tickets"),
    alias("events/new/policy", "create/guests-tickets"),
    alias("events/new/chat-ai", "create/chat-ai"),
    alias("events/new/promotion", "create/preview-publish"),
    alias("events/new/preview", "create/preview-publish"),
    alias("events/new/publish", "create/preview-publish"),
    alias("events/new/submit", "create/preview-publish"),
    alias("events/ai", "ai-builder/prompt"),
    alias("events/ai/prompt", "ai-builder/prompt"),
    alias("events/ai/plan", "ai-builder/generated-plan"),
    alias("events/ai/confirm", "ai-builder/review-edit"),
    surfaceAlias(
      "events/ai/success",
      "ai-builder",
      routeSurface(
        "events/ai/success",
        "AI draft ready",
        "AI draft created and ready to continue in the 5-step wizard.",
        "wizard_step",
        "ai_builder",
        ["create-v4"],
      ),
    ),
    alias("venues", "venue-finder"),
    alias("venues/find", "venue-finder"),
    alias(/^venues\/[^/]+\/preview$/, "venue-detail"),
    alias("venue-requests/new", "venue-requests"),
    surfaceAlias(
      /^venues\/[^/]+\/unavailable$/,
      "venue-finder",
      routeSurface(
        "venue-unavailable",
        "External Venue Unavailable",
        "Disabled state for venues with no external events policy.",
        "detail_panel",
        "venues",
        ["ORG-11"],
      ),
    ),
    alias(/^events\/[^/]+\/approval$/, "approval-tracker"),
    alias("venue-requests", "venue-requests"),
    surfaceAlias(
      /^venue-requests\/[^/]+$/,
      "venue-requests",
      routeSurface(
        "venue-request-thread",
        "Venue Request Detail Thread",
        "Organizer to venue owner access request thread and history.",
        "drawer",
        "approvals",
        ["ORG-26"],
      ),
    ),
    alias(/^events\/[^/]+$/, "workspace"),
    surfaceAlias(/^events\/[^/]+\/guests$/, "events", routeSurface("guests", "Guests", "Guest list, applications, waitlist and check-in.", "tab", "participants", ["v4"])),
    surfaceAlias(/^events\/[^/]+\/chat$/, "events", routeSurface("chat", "Chat", "Event chat, announcements and AI draft replies.", "tab", "chats", ["v4"])),
    surfaceAlias(/^events\/[^/]+\/promote$/, "events", routeSurface("promote", "Promote", "Boost, share link, promo code and AI promo copy.", "tab", "promotion", ["v4"])),
    surfaceAlias(/^events\/[^/]+\/money$/, "events", routeSurface("event-money", "Money", "Event revenue, refunds and payout rows.", "tab", "finance", ["v4"])),
    surfaceAlias(/^events\/[^/]+\/workspace-settings$/, "events", routeSurface("workspace-settings", "Settings", "Event AI mode, tickets, capacity and settings.", "tab", "generic", ["v4"])),
    surfaceAlias(/^events\/[^/]+\/settings$/, "events", routeSurface("workspace-settings", "Settings", "Event AI mode, tickets, capacity and settings.", "tab", "generic", ["v4"])),
    surfaceAlias(
      /^events\/[^/]+\/history$/,
      "events",
      routeSurface(
        "event-version-history",
        "Event Version History",
        "History of event field changes and approval-sensitive edits.",
        "detail_panel",
        "generic",
        ["ORG-29"],
      ),
    ),
    surfaceAlias(/^events\/[^/]+\/applications$/, "events", routeSurface("guests", "Guests", "Guest list, applications, waitlist and check-in.", "tab", "participants", ["v4"])),
    alias(/^participants\/[^/]+$/, "participant-detail"),
    surfaceAlias(/^events\/[^/]+\/waitlist$/, "events", routeSurface("guests", "Guests", "Guest list, applications, waitlist and check-in.", "tab", "participants", ["v4"])),
    surfaceAlias(/^events\/[^/]+\/check-in$/, "events", routeSurface("guests", "Guests", "Guest list, applications, waitlist and check-in.", "tab", "participants", ["v4"])),
    surfaceAlias(
      /^events\/[^/]+\/check-in\/qr$/,
      "events",
      routeSurface(
        "guests",
        "Guests",
        "Guest list, applications, waitlist and check-in.",
        "tab",
        "participants",
        ["v4"],
      ),
    ),
    surfaceAlias(
      /^events\/[^/]+\/check-in\/manual$/,
      "events",
      routeSurface(
        "guests",
        "Guests",
        "Guest list, applications, waitlist and check-in.",
        "tab",
        "participants",
        ["v4"],
      ),
    ),
    surfaceAlias(/^events\/[^/]+\/refunds$/, "events", routeSurface("event-money", "Money", "Event revenue, refunds and payout rows.", "tab", "finance", ["v4"])),
    surfaceAlias(/^events\/[^/]+\/tickets$/, "events", routeSurface("workspace-settings", "Settings", "Event AI mode, tickets, capacity and settings.", "tab", "generic", ["v4"])),
    surfaceAlias(/^events\/[^/]+\/promo-codes$/, "events", routeSurface("promote", "Promote", "Boost, share link, promo code and AI promo copy.", "tab", "promotion", ["v4"])),
    surfaceAlias(/^events\/[^/]+\/announcements$/, "events", routeSurface("chat", "Chat", "Event chat, announcements and AI draft replies.", "tab", "chats", ["v4"])),
    alias("inbox", "direct-messages"),
    alias("inbox/ai-drafts", "ai-draft-replies"),
    alias(/^ai-agents\/event\/[^/]+$/, "event-ai-agent"),
    alias("ai-agents/organizer", "organizer-ai-agent"),
    alias("ai/knowledge", "knowledge-base"),
    alias("ai/test", "ai-test-conversation"),
    surfaceAlias(
      "ai/analytics",
      "ai-agents",
      routeSurface(
        "ai-analytics",
        "AI Analytics",
        "Questions answered, conversions, handoffs and failed answers.",
        "tab",
        "ai_agents",
        ["ORG-49"],
      ),
    ),
    alias("promotion/new", "campaign-builder"),
    alias("promotion/creative", "creative-studio"),
    surfaceAlias(
      "promotion/targeting",
      "promotion",
      routeSurface(
        "promotion-targeting",
        "Targeting & Budget",
        "Audience, geography, schedule and spend limits.",
        "tab",
        "promotion",
        ["ORG-53"],
      ),
    ),
    alias(/^promotion\/[^/]+\/analytics$/, "campaign-analytics"),
    surfaceAlias(
      "payouts/ledger",
      "payouts",
      routeSurface(
        "payout-ledger",
        "Ledger & Fees",
        "Revenue source of truth, fees and refund adjustments.",
        "tab",
        "finance",
        ["ORG-56"],
      ),
    ),
    alias(/^events\/[^/]+\/payouts$/, "event-payouts"),
    alias("payouts/disputes", "disputes"),
    alias("profile/edit", "profile"),
    alias("profile/preview", "public-profile-preview"),
    alias("audit", "audit-log"),
    surfaceAlias(
      /^events\/[^/]+\/cancel$/,
      "events",
      routeSurface(
        "cancel-event",
        "Cancel Event Flow",
        "Cancellation with refund impact, notifications and audit.",
        "drawer",
        "finance",
        ["ORG-64"],
      ),
    ),
    surfaceAlias(
      "empty",
      "dashboard",
      routeSurface(
        "empty-first-launch",
        "Empty First Launch",
        "New organizer empty state with next best action.",
        "detail_panel",
        "dashboard",
        ["ORG-65"],
      ),
    ),
  ],
  venue_owner: [
    alias("venues", "places"),
    alias("my-venues", "places"),
    alias("add-claim", "places"),
    alias("add-venue", "places"),
    alias("claim-venue", "places"),
    alias("approvals", "requests"),
    alias("organizer-access", "requests"),
    alias("event-requests", "requests"),
    alias("inbox", "requests"),
    alias("external-events", "requests"),
    alias("analytics", "places"),
    alias("team", "places"),
    alias("settings", "places"),
    alias("audit", "places"),
    alias("audit-log", "places"),
    alias("venues/new", "add-claim"),
    alias("venues/claim/search", "claim-venue"),
    alias("venues/new/basics", "add-venue"),
    surfaceAlias(
      "venues/claim/evidence",
      "add-claim",
      routeSurface(
        "claim-evidence",
        "Claim Evidence Upload",
        "Upload ownership proof for moderator verification.",
        "tab",
        "create",
        ["VEN-06"],
      ),
    ),
    alias(/^claims\/[^/]+\/status$/, "claim-status"),
    surfaceAlias(
      /^claims\/[^/]+\/needs-info$/,
      "add-claim",
      routeSurface(
        "claim-needs-info",
        "Claim Needs Info State",
        "Moderator requested more ownership evidence.",
        "tab",
        "claims",
        ["VEN-08"],
      ),
    ),
    alias(/^venues\/[^/]+$/, "venue-detail"),
    alias(/^venues\/[^/]+\/edit$/, "edit-profile"),
    alias(/^venues\/[^/]+\/photos$/, "photos"),
    alias(/^venues\/[^/]+\/address$/, "address-map"),
    surfaceAlias(
      /^venues\/[^/]+\/capacity$/,
      "venues",
      routeSurface("venue-capacity", "Capacity & Layouts", "Capacity by layout and event type.", "tab", "venue_detail", ["VEN-13"]),
    ),
    surfaceAlias(
      /^venues\/[^/]+\/amenities$/,
      "venues",
      routeSurface("venue-amenities", "Amenities", "Sound, stage, bar, food, Wi-Fi and equipment.", "tab", "venue_detail", ["VEN-14"]),
    ),
    alias(/^venues\/[^/]+\/rules$/, "rules"),
    alias(/^venues\/[^/]+\/accessibility$/, "accessibility"),
    alias(/^venues\/[^/]+\/availability$/, "availability"),
    alias(/^venues\/[^/]+\/access-policy$/, "access-policy"),
    surfaceAlias(
      /^venues\/[^/]+\/policy\/organizers$/,
      "venues",
      routeSurface("policy-organizers", "Policy: Approve Organizers", "Owner approves organizer once for this venue.", "tab", "policy", ["VEN-19"]),
    ),
    surfaceAlias(
      /^venues\/[^/]+\/policy\/events$/,
      "venues",
      routeSurface("policy-events", "Policy: Moderate Every Event", "Every external event goes through owner review.", "tab", "policy", ["VEN-20"]),
    ),
    surfaceAlias(
      /^venues\/[^/]+\/policy\/closed$/,
      "venues",
      routeSurface("policy-closed", "Policy: No External Events", "External organizers cannot create events here.", "tab", "policy", ["VEN-21"]),
    ),
    alias(/^venues\/[^/]+\/approved-organizers$/, "approved-organizers"),
    alias(/^venues\/[^/]+\/blocked-organizers$/, "blocked-organizers"),
    alias("approvals/organizers", "organizer-access"),
    alias(/^approvals\/organizers\/[^/]+$/, "organizer-access-detail"),
    alias("approvals/events", "event-requests"),
    alias(/^approvals\/events\/[^/]+$/, "event-request-detail"),
    surfaceAlias(
      /^approvals\/events\/[^/]+\/request-changes$/,
      "organizer-access",
      routeSurface("request-changes", "Request Changes Drawer", "Specific venue-scoped requested changes with reason.", "drawer", "event_detail", ["VEN-28"]),
    ),
    alias("calendar/month", "calendar"),
    alias("calendar/week", "calendar-week"),
    alias("calendar/conflicts", "conflicts"),
    alias(/^external-events\/[^/]+$/, "external-event-detail"),
    surfaceAlias(
      /^external-events\/[^/]+\/ops-thread$/,
      "external-events",
      routeSurface("venue-ops-thread", "Venue Ops Thread", "Organizer to venue owner operational thread.", "drawer", "chats", ["VEN-34"]),
    ),
    alias("ai-agent/knowledge", "knowledge-base"),
    alias("ai-agent/test", "ai-agent/test-conversation"),
    surfaceAlias(
      "promotion/new",
      "promotion",
      routeSurface("venue-campaign-builder", "Venue Campaign Builder", "Campaign for venue or owner event.", "action", "promotion", ["VEN-40"]),
    ),
    alias("audit", "audit-log"),
    alias(/^venues\/[^/]+\/preview$/, "public-preview"),
    surfaceAlias(
      /^venues\/[^/]+\/limited$/,
      "venues",
      routeSurface("ownership-limited", "Ownership Limited / Suspended State", "Before claim approval or after suspension.", "detail_panel", "venue_detail", ["VEN-47"]),
    ),
  ],
  moderator: [
    alias("events", "dashboard"),
    alias("complaints", "reports"),
    alias("chat-moderation", "reports"),
    alias("chats", "reports"),
    alias("evidence-vault", "reports"),
    alias("claims", "claims"),
    alias("claims/organizations", "claims"),
    alias("claims/venues", "claims"),
    alias("ai-safety", "reports"),
    alias("promotion-review", "reports"),
    alias("enforcement", "history"),
    alias("appeals", "history"),
    alias("policy-rules", "history"),
    alias("audit", "history"),
    alias("audit-log", "history"),
    alias(/^events\/[^/]+$/, "event-approval-detail"),
    surfaceAlias(
      /^events\/[^/]+\/content-scan$/,
      "events",
      routeSurface("event-content-scan", "Event Content Scan", "AI/rule scan of event text, media and policies.", "drawer", "event_detail", ["MOD-04"]),
    ),
    alias(/^events\/[^/]+\/request-changes$/, "event-change-request"),
    alias(/^complaints\/[^/]+$/, "complaint-detail"),
    surfaceAlias(
      /^incidents\/[^/]+\/timeline$/,
      "complaints",
      routeSurface("incident-timeline", "Incident Timeline", "Chronology across event, chat and user reports.", "drawer", "complaints", ["MOD-08"]),
    ),
    alias("chats", "chat-moderation"),
    alias(/^chats\/[^/]+$/, "chat-moderation-detail"),
    surfaceAlias(
      /^chats\/[^/]+\/remove$/,
      "chat-moderation",
      routeSurface("remove-message", "Hide / Remove Message Flow", "Legal-sensitive removal with evidence and reason.", "drawer", "chats", ["MOD-11"]),
    ),
    alias("evidence", "evidence-vault"),
    surfaceAlias(
      /^evidence\/[^/]+$/,
      "evidence-vault",
      routeSurface("evidence-item-detail", "Evidence Item Detail", "Original content, hash and access log.", "detail_panel", "evidence", ["MOD-13"]),
    ),
    alias("claims/organizations", "organization-claims"),
    alias(/^claims\/organizations\/[^/]+$/, "organization-claim-detail"),
    alias("claims/venues", "venue-claims"),
    alias(/^claims\/venues\/[^/]+$/, "venue-claim-detail"),
    alias(/^ai-safety\/conversations\/[^/]+$/, "ai-conversation-review"),
    alias(/^ai-safety\/disable\/[^/]+$/, "ai-agent-enforcement"),
    alias("promotion", "promotion-review"),
    alias(/^promotion\/[^/]+$/, "promotion-review-detail"),
    surfaceAlias(
      /^promotion\/[^/]+\/scan$/,
      "promotion-review",
      routeSurface("promo-policy-scan", "Promo Creative Policy Scan", "Scan misleading, illegal, extremist or political content.", "drawer", "promotion", ["MOD-23"]),
    ),
    surfaceAlias(
      "enforcement/block",
      "enforcement",
      routeSurface("block-flow", "Block User / Org / Event Flow", "Block with policy reason, scope and duration.", "drawer", "enforcement", ["MOD-26"]),
    ),
    alias(/^enforcement\/[^/]+$/, "enforcement-action-detail"),
    alias(/^appeals\/[^/]+$/, "appeal-detail"),
    alias("policy-rules/new", "risk-rule-builder"),
    surfaceAlias(
      "risk-simulator",
      "policy-rules",
      routeSurface("risk-simulator", "Risk Scoring Simulator", "Test event, chat or promo against policy rules.", "tab", "rules", ["MOD-31"]),
    ),
    alias("audit", "audit-log"),
    alias("settings", "team-settings"),
    surfaceAlias("workload", "audit-log", routeSurface("workload", "Workload Assignment", "Assign cases by SLA, severity and team.", "tab", "team", ["MOD-34"])),
    surfaceAlias("legal", "dashboard", routeSurface("legal", "Legal Escalation Queue", "Critical legal and policy escalations.", "tab", "moderation_queue", ["MOD-35"])),
    surfaceAlias("safety-keywords", "policy-rules", routeSurface("safety-keywords", "Safety Keywords Config", "Manage keywords and topics for flags.", "tab", "rules", ["MOD-36"])),
    surfaceAlias("platform-health", "audit-log", routeSurface("platform-health", "Platform Health Overview", "Queue health, reports trend and enforcement load.", "tab", "finance", ["MOD-37"])),
    surfaceAlias("sla", "audit-log", routeSurface("sla", "Decision SLA Dashboard", "SLA performance by queue and severity.", "tab", "finance", ["MOD-38"])),
    surfaceAlias("bulk-warning", "dashboard", routeSurface("bulk-warning", "Bulk Review Not Allowed Warning", "Prevent unsafe bulk approval of risky cases.", "detail_panel", "moderation_queue", ["MOD-39"])),
    surfaceAlias(/^finance-context\/[^/]+$/, "audit-log", routeSurface("finance-context", "Limited Finance Context", "Finance shown only for fraud/dispute cases.", "drawer", "finance", ["MOD-40"])),
    surfaceAlias("reports/severity", "complaints", routeSurface("reports-severity", "Reports by Severity", "Complaint and report distribution.", "tab", "complaints", ["MOD-41"])),
    surfaceAlias("repeat-offenders", "audit-log", routeSurface("repeat-offenders", "Repeat Offender Graph", "Linked cases across users, orgs and events.", "drawer", "complaints", ["MOD-42"])),
    surfaceAlias("cases/merge", "complaints", routeSurface("case-merge", "Case Merge / Split", "Merge duplicates or split unrelated reports.", "drawer", "complaints", ["MOD-43"])),
    surfaceAlias(/^escalations\/[^/]+\/handoff$/, "dashboard", routeSurface("escalation-handoff", "Escalation Handoff", "Hand off to senior or legal with context.", "drawer", "moderation_queue", ["MOD-44"])),
    surfaceAlias("empty", "dashboard", routeSurface("empty-review-queue", "Empty Review Queue", "No moderation cases state.", "detail_panel", "moderation_queue", ["MOD-45"])),
  ],
};

const rawRoleScreens: Record<AdminRole, AdminScreenDefinition[]> = {
  organizer: [
    ...organizerScreens,
    {
      slug: "messages",
      title: "Messages",
      description: "Event questions, venue threads and replies that need attention.",
      navGroup: "Workspace",
      variant: "chats",
      requiredRole: "organizer",
    },
    {
      slug: "money",
      title: "Money",
      description: "Revenue, refunds, payout date and tax/KYC tasks.",
      navGroup: "Workspace",
      variant: "finance",
      requiredRole: "organizer",
    },
  ],
  venue_owner: [
    ...venueOwnerScreens,
    {
      slug: "places",
      title: "Places",
      description: "Your places, verification status, access rules and public preview.",
      navGroup: "Workspace",
      variant: "venues",
      requiredRole: "venue_owner",
    },
    {
      slug: "requests",
      title: "Requests",
      description: "Event requests and organizer access requests that need a decision.",
      navGroup: "Workspace",
      variant: "approvals",
      requiredRole: "venue_owner",
    },
  ],
  moderator: [
    ...moderatorScreens,
    {
      slug: "reports",
      title: "Reports",
      description: "Reports grouped by urgency and simple case type.",
      navGroup: "Workspace",
      variant: "complaints",
      requiredRole: "moderator",
    },
    {
      slug: "claims",
      title: "Claims",
      description: "Ownership cases for organizations and places.",
      navGroup: "Workspace",
      variant: "claims",
      requiredRole: "moderator",
    },
    {
      slug: "history",
      title: "History",
      description: "Recent case decisions and saved review notes.",
      navGroup: "Workspace",
      variant: "audit",
      requiredRole: "moderator",
    },
  ],
};

function surfaceFromScreen(
  role: AdminRole,
  screen: AdminScreenDefinition,
): AdminScreenSurface {
  const config = childSurfaces[role][screen.slug];
  return {
    slug: screen.slug,
    title: screen.title,
    description: screen.description,
    surfaceType: config?.surfaceType ?? (screen.detail ? "detail_panel" : "tab"),
    variant: screen.variant,
    detail: screen.detail,
    destructiveActions: screen.destructiveActions,
    partialData: screen.partialData,
    prototypeRefs: config?.prototypeRefs ?? screen.prototypeRefs,
  };
}

function buildTabs(role: AdminRole, parent: AdminScreenDefinition): AdminScreenSurface[] {
  if (role === "organizer" && parent.slug === "events") {
    return [
      {
        slug: "events",
        title: "All events",
        description: "Drafts, upcoming and past events.",
        surfaceType: "page",
        variant: "events",
      },
      routeSurface("workspace", "Overview", "Main event summary and next best action.", "detail_panel", "event_detail", ["v4"]),
      routeSurface("guests", "Guests", "Applications, waitlist, check-in, refunds and guest actions.", "tab", "participants", ["v4"]),
      routeSurface("chat", "Chat", "Event chat, announcements and AI draft replies.", "tab", "chats", ["v4"]),
      routeSurface("promote", "Promote", "Boosts, share links, promo codes and AI promo copy.", "tab", "promotion", ["v4"]),
      routeSurface("event-money", "Money", "Event revenue, refunds and payout rows.", "tab", "finance", ["v4"]),
      routeSurface("workspace-settings", "Settings", "Tickets, capacity, chat AI mode and event settings.", "tab", "generic", ["v4"]),
    ];
  }

  const ownSurface: AdminScreenSurface = {
    slug: parent.slug,
    title:
      parent.slug === "dashboard"
        ? "Overview"
        : primaryTitleOverrides[role][parent.slug] ?? parent.title,
    description: parent.description,
    surfaceType: "page",
    variant: parent.variant,
    partialData: parent.partialData,
    destructiveActions: parent.destructiveActions,
    prototypeRefs: parent.prototypeRefs,
  };
  const childTabs = rawRoleScreens[role]
    .filter((screen) => childSurfaces[role][screen.slug]?.parentSlug === parent.slug)
    .map((screen) => surfaceFromScreen(role, screen));
  const supplemental = extraSurfaces[role][parent.slug] ?? [];
  return [ownSurface, ...childTabs, ...supplemental];
}

function enhanceScreens(role: AdminRole): AdminScreenDefinition[] {
  const primarySet = new Set(primaryNavSlugs[role]);
  return rawRoleScreens[role].map((screen) => {
    const childConfig = childSurfaces[role][screen.slug];
    const isPrimaryNav = primarySet.has(screen.slug);
    const title = isPrimaryNav
      ? (primaryTitleOverrides[role][screen.slug] ?? screen.title)
      : screen.title;
    return {
      ...screen,
      title,
      isPrimaryNav,
      parentSlug: childConfig?.parentSlug,
      surfaceType: childConfig?.surfaceType ?? (isPrimaryNav ? "page" : screen.detail ? "detail_panel" : "tab"),
      prototypeRefs: childConfig?.prototypeRefs ?? screen.prototypeRefs,
      tabs: isPrimaryNav ? buildTabs(role, { ...screen, title }) : undefined,
    };
  });
}

export const roleScreens: Record<AdminRole, AdminScreenDefinition[]> = {
  organizer: enhanceScreens("organizer"),
  venue_owner: enhanceScreens("venue_owner"),
  moderator: enhanceScreens("moderator"),
};

function findExtraSurface(role: AdminRole, slug: string) {
  for (const [parentSlug, surfaces] of Object.entries(extraSurfaces[role])) {
    const surface = surfaces.find((item) => item.slug === slug);
    if (surface) return { parentSlug, surface };
  }
  return undefined;
}

function findRouteAlias(role: AdminRole, slug: string) {
  return v3RouteAliases[role].find((item) => item.pattern.test(slug));
}

export function getScreen(role: AdminRole, slug?: string): AdminScreenDefinition {
  const normalized = slug && slug.length > 0 ? slug : "dashboard";
  const aliasMatch = findRouteAlias(role, normalized);

  if (aliasMatch?.parentSlug && aliasMatch.surface) {
    const parent = roleScreens[role].find((screen) => screen.slug === aliasMatch.parentSlug);
    if (parent) {
      return {
        ...parent,
        activeSurface: aliasMatch.surface,
        resolvedFromSlug: normalized,
      };
    }
  }

  const lookupSlug = aliasMatch?.targetSlug ?? normalized;
  const found = roleScreens[role].find((screen) => screen.slug === lookupSlug);
  if (found?.isPrimaryNav) return found;
  if (found?.parentSlug) {
    const parent = roleScreens[role].find((screen) => screen.slug === found.parentSlug);
    if (parent) {
      return {
        ...parent,
        activeSurface: surfaceFromScreen(role, found),
        resolvedFromSlug: normalized,
      };
    }
  }

  const extra = findExtraSurface(role, lookupSlug);
  if (extra) {
    const parent = roleScreens[role].find((screen) => screen.slug === extra.parentSlug);
    if (parent) {
      return {
        ...parent,
        activeSurface: extra.surface,
        resolvedFromSlug: normalized,
      };
    }
  }

  return {
    slug: normalized,
    title: normalized
      .split("-")
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join(" "),
    description:
      "This workspace page is available for compatibility and opens the closest simple task view.",
    navGroup: "Другие",
    variant: "generic",
    requiredRole: role,
    isPrimaryNav: false,
    surfaceType: "page",
    destructiveActions:
      normalized.includes("delete") ||
      normalized.includes("block") ||
      normalized.includes("reject") ||
      normalized.includes("refund") ||
      normalized.includes("dispute"),
  };
}

export function getPrimaryNavigation(role: AdminRole) {
  const bySlug = new Map(roleScreens[role].map((screen) => [screen.slug, screen]));
  return primaryNavSlugs[role]
    .map((slug) => bySlug.get(slug))
    .filter((screen): screen is AdminScreenDefinition => Boolean(screen));
}

export function groupedScreens(role: AdminRole) {
  return getPrimaryNavigation(role).reduce<Record<string, AdminScreenDefinition[]>>(
    (groups, screen) => {
      groups[screen.navGroup] = groups[screen.navGroup] ?? [];
      groups[screen.navGroup].push(screen);
      return groups;
    },
    {},
  );
}
