// Industry-standard 3-level taxonomy
// Extracted from Humanitix & Eventbrite reverse engineering
// 20 Event Types × 21 Categories × 215+ Sub-categories

export interface TaxonomyOption {
  value: string;
  label: string;
}

// ─── Level 1: Event Types (20) ───
export const eventTypes: TaxonomyOption[] = [
  { value: "appearanceOrSigning", label: "Appearance or Signing" },
  { value: "attraction", label: "Attraction" },
  { value: "campTripOrRetreat", label: "Camp, Trip or Retreat" },
  { value: "classTrainingOrWorkshop", label: "Class, Training or Workshop" },
  { value: "concertOrPerformance", label: "Concert or Performance" },
  { value: "conference", label: "Conference" },
  { value: "convention", label: "Convention" },
  { value: "dinnerOrGala", label: "Dinner or Gala" },
  { value: "festivalOrFair", label: "Festival or Fair" },
  { value: "gameOrCompetition", label: "Game or Competition" },
  { value: "meetingOrNetworkingEvent", label: "Meeting or Networking Event" },
  { value: "partyOrSocialGathering", label: "Party or Social Gathering" },
  { value: "raceOrEnduranceEvent", label: "Race or Endurance Event" },
  { value: "rally", label: "Rally" },
  { value: "screening", label: "Screening" },
  { value: "seminarOrTalk", label: "Seminar or Talk" },
  { value: "tour", label: "Tour" },
  { value: "tournament", label: "Tournament" },
  { value: "tradeShowConsumerShowOrExpo", label: "Trade Show, Consumer Show or Expo" },
  { value: "other", label: "Other" },
];

// ─── Level 2: Event Categories (21) ───
export const eventCategories: TaxonomyOption[] = [
  { value: "autoBoatAndAir", label: "Auto, Boat & Air" },
  { value: "businessAndProfessional", label: "Business & Professional" },
  { value: "charityAndCauses", label: "Charity & Causes" },
  { value: "communityAndCulture", label: "Community & Culture" },
  { value: "familyAndEducation", label: "Family & Education" },
  { value: "fashionAndBeauty", label: "Fashion & Beauty" },
  { value: "filmMediaAndEntertainment", label: "Film, Media & Entertainment" },
  { value: "foodAndDrink", label: "Food & Drink" },
  { value: "governmentAndPolitics", label: "Government & Politics" },
  { value: "healthAndWellness", label: "Health & Wellness" },
  { value: "hobbiesAndSpecialInterest", label: "Hobbies & Special Interest" },
  { value: "homeAndLifestyle", label: "Home & Lifestyle" },
  { value: "music", label: "Music" },
  { value: "performingAndVisualArts", label: "Performing & Visual Arts" },
  { value: "religionAndSpirituality", label: "Religion & Spirituality" },
  { value: "schoolActivities", label: "School Activities" },
  { value: "scienceAndTechnology", label: "Science & Technology" },
  { value: "seasonalAndHoliday", label: "Seasonal & Holiday" },
  { value: "sportsAndFitness", label: "Sports & Fitness" },
  { value: "travelAndOutdoor", label: "Travel & Outdoor" },
  { value: "other", label: "Other" },
];

// ─── Level 3: Event Sub-categories by Category ───
export const eventSubCategories: Record<string, string[]> = {
  autoBoatAndAir: ["Air", "Auto", "Boat", "Motorcycle", "Other"],
  businessAndProfessional: [
    "Career",
    "Construction",
    "Design",
    "Educators",
    "Environment & Sustainability",
    "Finance",
    "Investment",
    "Media",
    "Medicine",
    "Non-profit & NGOs",
    "Real Estate",
    "Sales & Marketing",
    "Startups & Small Business",
    "Other",
  ],
  charityAndCauses: [
    "Animal Welfare",
    "Disaster Relief",
    "Education",
    "Environment",
    "Healthcare",
    "Human Rights",
    "International Aid",
    "Poverty",
    "Other",
  ],
  communityAndCulture: [
    "City/Town",
    "County",
    "First Nations",
    "Heritage",
    "Historic",
    "LGBT",
    "Language",
    "Medieval",
    "Nationality",
    "Renaissance",
    "State",
    "Other",
  ],
  familyAndEducation: [
    "Alumni",
    "Baby",
    "Children & Youth",
    "Education",
    "Parenting",
    "Parents Association",
    "Reunion",
    "Senior Citizen",
    "Other",
  ],
  fashionAndBeauty: ["Accessories", "Beauty", "Bridal", "Fashion", "Other"],
  filmMediaAndEntertainment: [
    "Adult",
    "Anime",
    "Comedy",
    "Comics",
    "Film",
    "Gaming",
    "TV",
    "Other",
  ],
  foodAndDrink: ["Beer", "Food", "Spirits", "Wine", "Other"],
  governmentAndPolitics: [
    "County/Municipal Government",
    "Democratic Party",
    "Federal Government",
    "International Affairs",
    "Military",
    "National Security",
    "Non-partisan",
    "Other Party",
    "Republican Party",
    "State Government",
    "Other",
  ],
  healthAndWellness: ["Medical", "Mental Health", "Personal Health", "Spa", "Yoga", "Other"],
  hobbiesAndSpecialInterest: [
    "Adult",
    "Anime/Comics",
    "Arts & Crafts",
    "Board Games",
    "Books",
    "DIY",
    "Drawing & Painting",
    "Gaming",
    "Knitting",
    "Photography",
    "Pottery",
    "Other",
  ],
  homeAndLifestyle: ["Dating", "Home & Garden", "Pets & Animals", "Other"],
  music: [
    "Acoustic",
    "Alternative",
    "Americana",
    "Bluegrass",
    "Blues",
    "Blues & Jazz",
    "Classical",
    "Country",
    "Cultural",
    "DJ/Dance",
    "Disco",
    "EDM",
    "EDM/Electronic",
    "Electronic",
    "Experimental",
    "Folk",
    "Funk",
    "Hip Hop/Rap",
    "Indie",
    "Jazz",
    "Latin",
    "Metal",
    "Opera",
    "Pop",
    "Psychedelic",
    "Punk/Hardcore",
    "R&B",
    "Reggae",
    "Religious/Spiritual",
    "Rock",
    "Singer/Songwriter",
    "Soul",
    "Top 40",
    "World",
    "Other",
  ],
  performingAndVisualArts: [
    "Ballet",
    "Comedy",
    "Craft",
    "Dance",
    "Design",
    "Fine Art",
    "Jewelry",
    "Literary Arts",
    "Musical",
    "Opera",
    "Orchestra",
    "Painting",
    "Sculpture",
    "Theatre",
    "Other",
  ],
  religionAndSpirituality: [
    "Agnosticism",
    "Atheism",
    "Buddhism",
    "Christianity",
    "Eastern Religion",
    "Folk Religions",
    "Hinduism",
    "Islam",
    "Judaism",
    "Mormonism",
    "Mysticism & Occult",
    "New Age",
    "Shintoism",
    "Sikhism",
    "Unaffiliated",
    "Other",
  ],
  schoolActivities: [
    "After School Care",
    "Awards",
    "Dance/Ball/Prom",
    "Dinner",
    "Fund Raiser",
    "Graduation",
    "Open Day",
    "Parking",
    "Public Speaker",
    "Raffle",
    "Sports",
    "Other",
  ],
  scienceAndTechnology: [
    "Biotech",
    "High Tech",
    "Medicine",
    "Mobile",
    "Robotics",
    "Science",
    "Social Media",
    "Other",
  ],
  seasonalAndHoliday: [
    "Autumn Events",
    "Christmas",
    "Easter",
    "Fall events",
    "Fathers Day",
    "Halloween/Haunt",
    "Hanukkah",
    "Independence Day",
    "Mothers Day",
    "New Year's Eve",
    "St. Patrick's Day",
    "Thanksgiving",
    "Other",
  ],
  sportsAndFitness: [
    "American Football",
    "Baseball",
    "Basketball",
    "Camps",
    "Cheer",
    "Cycling",
    "Exercise",
    "Fighting & Martial Arts",
    "Football",
    "Golf",
    "Hockey",
    "Lacrosse",
    "Motorsports",
    "Mountain Biking",
    "Obstacles",
    "Rugby",
    "Running",
    "Snow Sports",
    "Softball",
    "Swimming & Water Sports",
    "Tennis",
    "Track & Field",
    "Volleyball",
    "Walking",
    "Weightlifting",
    "Wrestling",
    "Yoga",
    "Other",
  ],
  travelAndOutdoor: [
    "Canoeing",
    "Climbing",
    "Hiking",
    "Kayaking",
    "Rafting",
    "Travel",
    "Other",
  ],
  other: [],
};

// ─── Currencies ───
export const currencies: TaxonomyOption[] = [
  { value: "USD", label: "USD ($) — US Dollar" },
  { value: "EUR", label: "EUR (€) — Euro" },
  { value: "GBP", label: "GBP (£) — British Pound" },
  { value: "RUB", label: "RUB (₽) — Russian Ruble" },
  { value: "KZT", label: "KZT (₸) — Kazakhstani Tenge" },
  { value: "GEL", label: "GEL (₾) — Georgian Lari" },
  { value: "UZS", label: "UZS (soʻm) — Uzbekistani Som" },
  { value: "TRY", label: "TRY (₺) — Turkish Lira" },
  { value: "AMD", label: "AMD (֏) — Armenian Dram" },
  { value: "AZN", label: "AZN (₼) — Azerbaijani Manat" },
];

// ─── Helpers ───
export function getCategoryLabel(value: string): string {
  return eventCategories.find((c) => c.value === value)?.label || value;
}

export function getTypeLabel(value: string): string {
  return eventTypes.find((t) => t.value === value)?.label || value;
}

export function getSubCategories(categoryValue: string): string[] {
  return eventSubCategories[categoryValue] || [];
}

// ─── Smart recommendations: Event Type → Categories ───
export const eventTypeToCategories: Record<string, string[]> = {
  appearanceOrSigning: ["filmMediaAndEntertainment", "music", "fashionAndBeauty", "performingAndVisualArts"],
  attraction: ["travelAndOutdoor", "performingAndVisualArts", "autoBoatAndAir", "communityAndCulture"],
  campTripOrRetreat: ["travelAndOutdoor", "healthAndWellness", "familyAndEducation", "sportsAndFitness"],
  classTrainingOrWorkshop: ["hobbiesAndSpecialInterest", "healthAndWellness", "foodAndDrink", "businessAndProfessional", "scienceAndTechnology"],
  concertOrPerformance: ["music", "performingAndVisualArts", "communityAndCulture", "seasonalAndHoliday"],
  conference: ["businessAndProfessional", "scienceAndTechnology", "healthAndWellness", "education"],
  convention: ["businessAndProfessional", "scienceAndTechnology", "hobbiesAndSpecialInterest"],
  dinnerOrGala: ["foodAndDrink", "charityAndCauses", "fashionAndBeauty", "communityAndCulture"],
  festivalOrFair: ["music", "foodAndDrink", "seasonalAndHoliday", "communityAndCulture", "filmMediaAndEntertainment"],
  gameOrCompetition: ["sportsAndFitness", "hobbiesAndSpecialInterest", "filmMediaAndEntertainment"],
  meetingOrNetworkingEvent: ["businessAndProfessional", "communityAndCulture", "scienceAndTechnology"],
  partyOrSocialGathering: ["music", "foodAndDrink", "fashionAndBeauty", "filmMediaAndEntertainment"],
  raceOrEnduranceEvent: ["sportsAndFitness", "charityAndCauses", "healthAndWellness"],
  rally: ["governmentAndPolitics", "communityAndCulture", "charityAndCauses"],
  screening: ["filmMediaAndEntertainment", "performingAndVisualArts", "communityAndCulture"],
  seminarOrTalk: ["businessAndProfessional", "scienceAndTechnology", "healthAndWellness", "communityAndCulture"],
  tour: ["travelAndOutdoor", "communityAndCulture", "performingAndVisualArts", "autoBoatAndAir"],
  tournament: ["sportsAndFitness", "gameOrCompetition", "hobbiesAndSpecialInterest"],
  tradeShowConsumerShowOrExpo: ["businessAndProfessional", "homeAndLifestyle", "fashionAndBeauty", "scienceAndTechnology"],
  other: [],
};

export function getRecommendedCategories(eventTypeValue: string): string[] {
  return eventTypeToCategories[eventTypeValue] || [];
}
