export const globalForbidden = [
  "This workspace page is available for compatibility",
  "OperationalStatesPanel",
  "AuditLogPanel",
  "Skeleton rows shown after 200ms",
  "Submitted event for approval",
  "RBAC",
  "permission context",
  "evidence vault",
  "risk score",
  "approval_gates",
  "blocked_until_gates_pass",
  "draft_replies",
  "kyc_required",
  "retainedHash",
  "evidenceId",
  "sha256",
];

const previewForbidden = ["Preview states", "Предпросмотр состояний"];

export const routeChecks = [
  { group: "Organizer", route: "/organizer", expected: ["Сегодня"], forbidden: previewForbidden },
  { group: "Organizer", route: "/organizer/events", expected: ["События"], forbidden: previewForbidden },
  { group: "Organizer", route: "/organizer/events/e1", expected: ["Обзор", "Гости", "Чат", "Промо", "Деньги", "Настройки"], forbidden: previewForbidden },
  { group: "Organizer", route: "/organizer/events/new", expected: ["Создать событие"], forbidden: previewForbidden },
  { group: "Organizer", route: "/organizer/events/ai", expected: ["Начать с ИИ"], forbidden: previewForbidden },
  { group: "Organizer", route: "/organizer/chats", expected: ["Сообщения"], forbidden: previewForbidden },
  { group: "Organizer", route: "/organizer/messages", expected: ["Сообщения"], forbidden: previewForbidden },
  { group: "Organizer", route: "/organizer/profile", redirectTo: "/organizer/profile/edit", expected: ["Профиль организатора"], forbidden: previewForbidden },
  { group: "Organizer", route: "/organizer/profile/edit", expected: ["Профиль организатора"], forbidden: previewForbidden },
  { group: "Organizer", route: "/organizer/profile/preview", expected: ["Профиль организатора"], forbidden: previewForbidden },
  { group: "Organizer", route: "/organizer/reviews", expected: ["Отзывы и доверие"], forbidden: previewForbidden },
  { group: "Organizer", route: "/organizer/money", expected: ["Деньги"], forbidden: previewForbidden },
  {
    group: "Organizer",
    route: "/organizer/analytics",
    expected: [
      "Аналитика",
      "Просмотры, гости, продажи и эффективность продвижения.",
      "Открыть события",
      "Эффективность событий",
      "Продвижение",
      "Аудитория",
      "Рекомендации",
    ],
    forbidden: [
      "Event Analytics",
      "Funnel, no-show, retention, revenue and conversion.",
      "Submitted event for approval",
      "Preview states",
      "Предпросмотр состояний",
    ],
  },
  { group: "Organizer", route: "/organizer/payouts", expected: ["Деньги"], forbidden: previewForbidden },
  {
    group: "Organizer",
    route: "/organizer/venues",
    expected: [
      "Площадки",
      "Найдите площадку для события или проверьте запросы владельцам.",
      "Мои запросы",
      "Можно запросить",
      "Не принимает заявки",
    ],
    forbidden: [
      "Venue Finder",
      "Venue Request",
      "Access Tracker",
      "approve_organizers",
      "moderate_every_event",
      "no_external_events",
      "Preview states",
      "Предпросмотр состояний",
    ],
  },
  { group: "Organizer legacy redirects", route: "/organizer/venues/find", redirectTo: "/organizer/venues", expected: ["Площадки"] },
  { group: "Organizer legacy redirects", route: "/organizer/requests", redirectTo: "/organizer/venues", expected: ["Площадки", "Мои запросы"] },

  {
    group: "Organizer",
    route: "/organizer/venue-requests",
    expected: ["Запросы площадок", "Новый запрос"],
    forbidden: [
      "This workspace page is available for compatibility",
      "Preview states",
      "Предпросмотр состояний",
      "OperationalStatesPanel",
      "AuditLogPanel",
      "OrganizerEdgeStates",
      "Submitted event for approval",
    ],
  },
  {
    group: "Organizer",
    route: "/organizer/venue-requests/vr_101",
    expected: ["Статус запроса", "Ждёт ответа владельца"],
    forbidden: [
      "This workspace page is available for compatibility",
      "Preview states",
      "Предпросмотр состояний",
      "OperationalStatesPanel",
      "AuditLogPanel",
      "OrganizerEdgeStates",
      "Submitted event for approval",
      "Needs attention",
      "Active events",
      "Pending payout",
    ],
  },

  { group: "Organizer legacy redirects", route: "/organizer/assistant", redirectTo: "/organizer/events/ai", expected: ["Начать с ИИ"] },
  { group: "Organizer legacy redirects", route: "/organizer/calendar", redirectTo: "/organizer/events", expected: ["События"] },
  { group: "Organizer legacy redirects", route: "/organizer/events/calendar", redirectTo: "/organizer/events", expected: ["События"] },
  { group: "Organizer legacy redirects", route: "/organizer/events/pipeline", redirectTo: "/organizer/events", expected: ["События"] },

  { group: "Owner", route: "/owner", expected: ["Сегодня"], forbidden: previewForbidden },
  { group: "Owner", route: "/venue-owner", redirectTo: "/owner", expected: ["Сегодня"], forbidden: previewForbidden },
  { group: "Owner", route: "/owner/places", expected: ["Площадки"], forbidden: previewForbidden },
  { group: "Owner", route: "/owner/venues", expected: ["Площадки"], forbidden: previewForbidden },
  { group: "Owner", route: "/owner/requests", expected: ["Заявки"], forbidden: previewForbidden },
  { group: "Owner", route: "/owner/calendar", expected: ["Календарь"], forbidden: previewForbidden },

  { group: "Owner legacy redirects", route: "/owner/approvals", redirectTo: "/owner/requests", expected: ["Заявки"] },
  { group: "Owner legacy redirects", route: "/owner/organizer-access", redirectTo: "/owner/requests", expected: ["Заявки"] },
  { group: "Owner legacy redirects", route: "/owner/event-requests", redirectTo: "/owner/requests", expected: ["Заявки"] },
  { group: "Owner legacy redirects", route: "/owner/approvals/organizers", redirectTo: "/owner/requests", expected: ["Заявки"] },
  { group: "Owner legacy redirects", route: "/owner/approvals/events", redirectTo: "/owner/requests", expected: ["Заявки"] },
  { group: "Owner legacy redirects", route: "/owner/calendar/month", redirectTo: "/owner/calendar", expected: ["Календарь"] },
  { group: "Owner legacy redirects", route: "/owner/calendar/week", redirectTo: "/owner/calendar", expected: ["Календарь"] },
  { group: "Owner legacy redirects", route: "/owner/calendar/conflicts", redirectTo: "/owner/calendar", expected: ["Календарь"] },

  { group: "Moderator", route: "/moderator", expected: ["Очередь"], forbidden: previewForbidden },
  { group: "Moderator", route: "/moderator/events", expected: ["События"], forbidden: previewForbidden },
  { group: "Moderator", route: "/moderator/hosts", redirectTo: "/moderator/claims/organizations", expected: ["Права"], forbidden: previewForbidden },
  { group: "Moderator", route: "/moderator/claims/organizations", expected: ["Права"], forbidden: previewForbidden },
  { group: "Moderator", route: "/moderator/claims/venues", expected: ["Права"], forbidden: previewForbidden },
  { group: "Moderator", route: "/moderator/claims/organizations/claim_1", expected: ["Права"], forbidden: previewForbidden },
  { group: "Moderator", route: "/moderator/claims/venues/claim_2", expected: ["Права"], forbidden: previewForbidden },
  { group: "Moderator", route: "/moderator/reports", expected: ["Жалобы"], forbidden: previewForbidden },
  { group: "Moderator legacy redirects", route: "/moderator/reports/severity", redirectTo: "/moderator/reports", expected: ["Жалобы"] },
  { group: "Moderator", route: "/moderator/complaints", expected: ["Жалобы"], forbidden: previewForbidden },
  { group: "Moderator", route: "/moderator/complaints/cmp_1", expected: ["Жалобы"], forbidden: previewForbidden },
  { group: "Moderator", route: "/moderator/chats", expected: ["Чаты"], forbidden: previewForbidden },
  { group: "Moderator", route: "/moderator/chat-moderation", expected: ["Чаты"], forbidden: previewForbidden },
  { group: "Moderator", route: "/moderator/chats/chat_1", expected: ["Чаты"], forbidden: previewForbidden },
  { group: "Moderator", route: "/moderator/chats/chat_1/remove", expected: ["Проверка сообщения"], forbidden: previewForbidden },

  { group: "Moderator legacy redirects", route: "/moderator/incidents", redirectTo: "/moderator", expected: ["Очередь"] },
  { group: "Moderator legacy redirects", route: "/moderator/incidents/demo", redirectTo: "/moderator", expected: ["Очередь"] },
  { group: "Moderator legacy redirects", route: "/moderator/cases/merge", redirectTo: "/moderator", expected: ["Очередь"] },
  { group: "Moderator legacy redirects", route: "/moderator/appeals/case_1", redirectTo: "/moderator/audit", expected: ["История"] },
  { group: "Moderator legacy redirects", route: "/moderator/enforcement/case_1", redirectTo: "/moderator/audit", expected: ["История"] },
  { group: "Moderator legacy redirects", route: "/moderator/policy-rules/rule_1", redirectTo: "/moderator/audit", expected: ["История"] },
];
