export const globalForbidden = [
  "This workspace page is available for compatibility",
  "Preview states",
  "Предпросмотр состояний",
  "OperationalStatesPanel",
  "AuditLogPanel",
  "Skeleton rows shown after 200ms",
  "Submitted event for approval",
  "RBAC",
  "permission context",
  "evidence vault",
  "risk score",
  "approval_gates",
  "blocked_until_gates_pass",
  "draft_replies",
  "kyc_required",
  "retainedHash",
  "evidenceId",
  "sha256",
];

export const routeChecks = [
  { group: "Organizer", route: "/organizer", expected: ["Сегодня"] },
  { group: "Organizer", route: "/organizer/events", expected: ["События"] },
  { group: "Organizer", route: "/organizer/events/e1", expected: ["Обзор", "Гости", "Чат", "Промо", "Деньги", "Настройки"] },
  { group: "Organizer", route: "/organizer/events/new", expected: ["Создать событие"] },
  { group: "Organizer", route: "/organizer/events/ai", expected: ["Начать с ИИ"] },
  { group: "Organizer", route: "/organizer/chats", expected: ["Сообщения"] },
  { group: "Organizer", route: "/organizer/messages", expected: ["Сообщения"] },
  { group: "Organizer", route: "/organizer/profile", redirectTo: "/organizer/profile/edit", expected: ["Профиль организатора"] },
  { group: "Organizer", route: "/organizer/profile/edit", expected: ["Профиль организатора"] },
  { group: "Organizer", route: "/organizer/profile/preview", expected: ["Профиль организатора"] },
  { group: "Organizer", route: "/organizer/reviews", expected: ["Отзывы и доверие"] },
  { group: "Organizer", route: "/organizer/money", expected: ["Деньги"] },
  { group: "Organizer", route: "/organizer/payouts", expected: ["Деньги"] },

  { group: "Owner", route: "/owner", expected: ["Сегодня"] },
  { group: "Owner", route: "/venue-owner", redirectTo: "/owner", expected: ["Сегодня"] },
  { group: "Owner", route: "/owner/places", expected: ["Площадки"] },
  { group: "Owner", route: "/owner/venues", expected: ["Площадки"] },
  { group: "Owner", route: "/owner/requests", expected: ["Заявки"] },
  { group: "Owner", route: "/owner/calendar", expected: ["Календарь"] },

  { group: "Owner legacy redirects", route: "/owner/approvals", redirectTo: "/owner/requests", expected: ["Заявки"] },
  { group: "Owner legacy redirects", route: "/owner/organizer-access", redirectTo: "/owner/requests", expected: ["Заявки"] },
  { group: "Owner legacy redirects", route: "/owner/event-requests", redirectTo: "/owner/requests", expected: ["Заявки"] },
  { group: "Owner legacy redirects", route: "/owner/approvals/organizers", redirectTo: "/owner/requests", expected: ["Заявки"] },
  { group: "Owner legacy redirects", route: "/owner/approvals/events", redirectTo: "/owner/requests", expected: ["Заявки"] },
  { group: "Owner legacy redirects", route: "/owner/calendar/month", redirectTo: "/owner/calendar", expected: ["Календарь"] },
  { group: "Owner legacy redirects", route: "/owner/calendar/week", redirectTo: "/owner/calendar", expected: ["Календарь"] },
  { group: "Owner legacy redirects", route: "/owner/calendar/conflicts", redirectTo: "/owner/calendar", expected: ["Календарь"] },

  { group: "Moderator", route: "/moderator", expected: ["Очередь"] },
  { group: "Moderator", route: "/moderator/events", expected: ["События"] },
  { group: "Moderator", route: "/moderator/hosts", redirectTo: "/moderator/claims/organizations", expected: ["Права"] },
  { group: "Moderator", route: "/moderator/claims/organizations", expected: ["Права"] },
  { group: "Moderator", route: "/moderator/claims/venues", expected: ["Права"] },
  { group: "Moderator", route: "/moderator/claims/organizations/claim_1", expected: ["Права"] },
  { group: "Moderator", route: "/moderator/claims/venues/claim_2", expected: ["Права"] },
  { group: "Moderator", route: "/moderator/reports", expected: ["Жалобы"] },
  { group: "Moderator", route: "/moderator/complaints", expected: ["Жалобы"] },
  { group: "Moderator", route: "/moderator/complaints/cmp_1", expected: ["Жалобы"] },
  { group: "Moderator", route: "/moderator/chats", expected: ["Чаты"] },
  { group: "Moderator", route: "/moderator/chat-moderation", expected: ["Чаты"] },
  { group: "Moderator", route: "/moderator/chats/chat_1", expected: ["Чаты"] },
  { group: "Moderator", route: "/moderator/chats/chat_1/remove", expected: ["Проверка сообщения"] },
];
